---
- hosts: compute
  become: yes
  gather_facts: no
  strategy: free

  tasks:

  - name: "compute-*.log logrotate entry"
    copy: src=files/compute-log-logrotate
          dest=/etc/logrotate.d/smc-compute-log
          owner=root group=root mode=644

  #- name : "remove logrotate"
  #  file:  path=/etc/logrotate.d/smc-compute-log
  #         state=absent

