---
- hosts: compute
  become: yes
  gather_facts: yes

  tasks:

  - apt: "name={{ item }} state=latest"
    tags: pip2
    with_items:
    - python-pip
    - python3-pip
    #- llvm-3.7
    #- llvm-3.7-dev # for numba

  - name: "update pip"
    tags: [ pip2, update ]
    pip: "executable=pip2 state=latest name=pip"

  - name: "additional pip2 packages"
    tags: [ pip2, update ]
    pip: executable=pip2
         state=latest
         umask=022
         name={{ item }}
    with_items:
    - theano
    - datasift
    - bokeh
    - twitter
    #- pygsl # broken
    - scikit-learn
    - statsmodels
    - clawpack
    - ctop
    - networkx
    - macs2
    - bayespy==0.3.6
    - pandasql
    - blaze
    - cvxpy

  - tags: [ pip2, update ]
    pip: executable=pip2
         umask=022
         name='git+https://github.com/jakevdp/JSAnimation.git'
         editable=false

  - name: "additional pip3 packages"
    tags: [ pip3, update ]
    pip: executable=pip3
         state=latest
         umask=022
         name={{ item }}
    with_items:
    - pip
    - twitter
    - sympy
    - bokeh
    - uncertainties
    - zope.interface
    - scikit-learn
    - datasift
    # - numba # TODO figure this out later, some error with llvm
    - holoviews
    - statsmodels
    - mygene
    - seaborn
    - biopython
    - bayespy
    - pandasql
    - blaze
    - cvxpy

  - name: "no sysinfo in MOTD"
    lineinfile: dest=/etc/update-motd.d/50-landscape-sysinfo
                line="exit 0"
                insertafter="^#!/bin/*"
                create=yes
    tags: motd

  - name: "Install https://github.com/williamstein/python-inotify"
    shell: |
        cd /tmp
        rm -rf python-inotify
        git clone https://github.com/williamstein/python-inotify
        cd python-inotify
        python setup.py install
    tags: inotify

  - name: "Install https://github.com/williamstein/bup-1 systemwide"
    shell: |
        cd /tmp
        rm -rf python-inotify bup-1
        git clone https://github.com/williamstein/bup-1
        cd bup-1
        make install
        cd ..
        rm -rf bup-1
    tags: bup1

  - name: "/etc/ssh/sshd_config: MaxStartups 128"
    lineinfile: dest=/etc/ssh/sshd_config
                insertafter="^#MaxStartups.*"
                line="MaxStartups 128"
    tags: ssh

  - name: "remove tmpreaper warning"
    lineinfile: dest=/etc/tmpreaper.conf
                backrefs=yes
                regexp="^SHOWWARNING=.*"
                line="#SHOWWARNING=true"
    tags: tmpreaper

  - name: "IPython with notebook and octave+bash kernel / remove ipython"
    apt: name=ipython state=absent
    tags: [ ipython, install, update ]
  - name: "IPython with notebook and octave+bash kernel / install from pip"
    tags: [ ipython, install, update ]
    pip: executable=pip2
         state=forcereinstall
         umask=022
         name={{ item }}
    with_items:
    - ipython
    - notebook
    - octave_kernel
    - bash_kernel
  - name: "fix permissions in all python2.7/dist-packages"
    tags: [ ipython, install, update ]
    shell: |
        cd /usr/local/lib/python2.7/dist-packages
        sudo chmod a+r -R .
        sudo find . -perm /u+x -execdir chmod a+x {} \;

  - name: "IPython3 in Python3"
    tags: [ ipython3, install, update ]
    pip: executable=pip3
         state=forcereinstall
         umask=022
         name={{ item }}
    with_items:
    - ipython
    - ipywidgets

  - name: "Special script to run python2 systemwide from within Sage"
    tags: python2sage
    copy: src=files/python2-ubuntu.sh
          dest=/usr/local/bin/python2-ubuntu
          owner=root group=root mode="u=rx,g=rx,o=rx"

  - name: "install pair-based-crypto library system-wide"
    tags: pairbasedcrypto
    ignore_errors: yes
    shell: |
        cd /tmp/
        umask 022
        wget https://crypto.stanford.edu/pbc/files/pbc-0.5.14.tar.gz
        tar xf pbc-0.5.14.tar.gz
        cd pbc-0.5.14
        ./configure --prefix=/usr
        sudo make install
        sudo rm -rf /tmp/pbc-0.5.14 /tmp/pbc-0.5.14.tar.gz

  - name: "cgroups configuration -- TODO maybe not needed in docker?"
    tags: cgroups
    lineinfile: dest=/etc/pam.d/common-session
                line="session optional pam_cgroup.so"
                insertafter=EOF

  - name: "install primesieve"
    tags: primesieve
    ignore_errors: yes
    shell: |
        cd /tmp/
        wget http://dl.bintray.com/kimwalisch/primesieve/primesieve-5.4.1.tar.gz
        tar xf primesieve-5.4.1.tar.gz
        cd primesieve-5.4.1
        ./configure
        make -j 1
        sudo make install
        rm -rf /tmp/primesieve*

  # this installs into sage!
  #- name: "install gap3"
  #  tags: gap3
  #  shell: "umask 022 && cd /projects/sage && wget http://webusers.imj-prg.fr/~jean.michel/gap3/gap3-jm5.zip && unzip gap3-jm5.zip && rm gap3-jm5.zip && mv gap3-jm5 gap3 && cd gap3"

  #- name: "gap3 symlink"
  #  tags: gap3
  #  file: src=/projects/sage/gap3/bin/gap.sh
  #        dest=/usr/local/bin/gap3
  #        state=link

  - name: "install opencv"
    tags: opencv
    ignore_errors: yes
    shell: |
        cd /tmp/
        rm -rf opencv
        mkdir opencv
        cd opencv
        git clone https://github.com/Itseez/opencv_contrib.git
        rm -rf opencv_contrib/modules/hdf
        git clone https://github.com/Itseez/opencv.git
        cd opencv
        mkdir build
        cd build
        time cmake -D WITH_FFMPEG=OFF -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON -D OPENCV_EXTRA_MODULES_PATH=/tmp/opencv/opencv_contrib/modules ..
        time make -j1
        sudo make install
        sudo sh -c 'echo /usr/local/lib > /etc/ld.so.conf.d/opencv.conf'
        sudo ldconfig
        cd /tmp
        rm -rf opencv

  # Plink (whole genome analysis, not the router!)
  - name: 'install plink'
    apt: name=plink install_recommends=yes
    tags: plink
  - name: 'symlink from p-link to plink'
    file: src=/usr/bin/p-link dest=/usr/bin/plink state=link
    tags: plink

  # Neovim from Github
  - name: "install neovim"
    tags: neovim
    ignore_errors: yes
    shell: |
        cd /tmp
        rm -rf neovim
        unset MAKE
        git clone --depth=1 https://github.com/neovim/neovim
        cd neovim
        make
        umask 022
        sudo make install
        rm -rf /tmp/neovim

  # Macaulay2
  - name: "install macaulay2 / apt packages"
    tags: macaulay2
    apt: "name={{ item }} install_recommends=yes state=latest"
    with_items:
    - libntl-dev
    - libntl5
    - libpari-gmp-tls4
    - libpari-dev
    - pari-gp2c
  - name: "install macaulay2 / deb binaries"
    tags: macaulay2
    ignore_errors: yes
    shell: |
        cd /tmp/
        rm -rf m2
        mkdir m2
        cd m2
        wget http://www.math.uiuc.edu/Macaulay2/Downloads/Common/Macaulay2-1.7-common.deb
        wget http://www.math.uiuc.edu/Macaulay2/Downloads/GNU-Linux/Ubuntu/Macaulay2-1.7-amd64-Linux-Ubuntu-14.10.deb
        sudo dpkg -i *.deb
        rm -rf /tmp/m2

  # Polymake
  - name: "polymake apt package dependencies"
    tags: polymake
    apt: "name={{ item }} state=latest install_recommends=yes"
    with_items:
    - ant
    - ant-optional
    - default-jdk
    - g++
    - libboost-dev
    - libgmp-dev
    - libgmpxx4ldbl
    - libmpfr-dev
    - libperl-dev
    - libsvn-perl
    - libterm-readline-gnu-perl
    - libxml-libxml-perl
    - libxml-libxslt-perl
    - libxml-perl
    - libxml-writer-perl
    - libxml2-dev
    - w3c-markup-validator
    - w3c-xsd-xslt
    - xsltproc
  #- name: "polymake installation"
  #  tags: polymake
  #  ignore_errors: yes
  #  shell: |
  #      cd /tmp/
  #      wget http://polymake.org/lib/exe/fetch.php/download/polymake-3.0r1.tar.bz2
  #      tar xf polymake-3.0r1.tar.bz2
  #      cd polymake-3.0/
  #      ./configure
  #      make
  - name: "polymake installation, from debian"
    apt: name=polymake state=latest install_recommends=yes

  # CRCMOD
  - name: "pip's crcmod -- critical for using google cloud storage #1"
    apt: name=crcmod state=absent
    tags: crcmod
  - name: "pip's crcmod -- critical for using google cloud storage #2"
    tags: crcmod
    pip: executable=pip2
         state=forcereinstall
         umask=022
         name=crcmod

  # X11
  - name: "git trac"
    tags: gittrac
    ignore_errors: yes
    shell: |
        cd /tmp/
        git clone https://github.com/sagemath/git-trac-command.git
        cd git-trac-command
        sudo setup.py install
        rm -rf /tmp/git-trac-command

  - name: "x11 setup"
    tags: x11
    lineinfile: dest=/etc/ssh/sshd_config
                insertafter=EOF
                line="X11UseLocalhost no"

# KWANT -- http://kwant-project.org/install
- hosts: compute
  become: yes
  gather_facts: no
  tags: kwant

  tasks:

  - name: 'KWANT apt repository'
    apt_repository: mode=644 repo='ppa:kwant-project/ppa'

  - name: 'install KWANT'
    tags: update
    apt: "name={{ item }} install_recommends=yes state=latest"
    with_items:
    - python-kwant-doc
    - python3-kwant

# GIAC (the authentication key is broken, hence we allow unauthenticated packages)
- hosts: compute
  become: yes
  gather_facts: no
  tags: giac

  tasks:

  - name: 'GIAC apt key -- seems to be broken, though'
    apt_key: url='http://www-fourier.ujf-grenoble.fr/~parisse/xcas_public_key.gpg'

  - name: 'GIAC repository'
    apt_repository: mode=644 repo='deb http://www-fourier.ujf-grenoble.fr/~parisse/debian/ stable main'

  - name: 'install GIAC'
    apt: "name={{ item }} allow_unauthenticated=yes install_recommends=yes state=latest"
    tags: update
    with_items:
    - giac
    - python-giacpy

# FEniCS
# add-apt-repository ppa:fenics-packages/fenics && apt-get update && apt-get install fenics
- hosts: compute
  become: yes
  gather_facts: no
  tags: fenics

  tasks:

  - name: 'FEniCS repository'
    apt_repository: mode=644 repo='ppa:fenics-packages/fenics'

  - name: 'install FEniCS'
    tags: update
    apt: name=fenics install_recommends=yes state=latest

# MPICH
- hosts: compute
  become: yes
  gather_facts: no
  tags: mpi

  tasks:

  - name: 'install mpich'
    tags: update
    apt: "name={{ item }} install_recommends=yes state=latest"
    with_items:
    - mpich
    - mpich-doc
    - libmpich-dev

  - name: 'update-alternativs for mpich binary'
    alternatives: name=mpi path=/usr/include/mpich
  - name: correct MPI executor is mpich
    alternatives: name=mpirun path=/usr/bin/mpirun.mpich

# PYPY
- hosts: compute
  become: yes
  gather_facts: no
  tags: pypy

  tasks:

  - name: 'pypy repository'
    apt_repository: mode=644 repo='ppa:pypy/ppa'

  - name: 'install pypy'
    tags: update
    apt: name=pypy install_recommends=yes state=latest

# Cantera
- hosts: compute
  become: yes
  gather_facts: no
  tags: cantera

  tasks:

  - name: 'Cantera repository'
    apt_repository: mode=644 repo='ppa:speth/cantera'

  - name: 'install Cantera'
    tags: update
    apt: "name={{ item }} install_recommends=yes state=latest"
    with_items:
    - cantera-python
    - cantera-python3
    - cantera-dev

# Heroku, see https://toolbelt.heroku.com/debian and read the shellscript
- hosts: compute
  become: yes
  gather_facts: no
  tags: heroku

  tasks:

  - name: 'heroku apt keys'
    apt_key: url='https://toolbelt.heroku.com/apt/release.key'
  - name: 'heroku apt-repository'
    apt_repository: mode=644 repo='deb http://toolbelt.heroku.com/ubuntu ./'
  - name: "heroku install"
    tags: update
    apt: name=heroku-toolbelt install_recommends=yes state=latest

# Obspy
- hosts: compute
  become: yes
  gather_facts: yes
  tags: obspy

  tasks:
  - name: "obspy keys"
    apt_key: url='https://raw.github.com/obspy/obspy/master/misc/debian/public.key'
  - name: "obspy apt repository"
    apt_repository: mode=644 repo='deb http://deb.obspy.org {{ ansible_distribution_release }} main'
  - name: 'install obspy packages'
    tags: update
    apt: "name={{ item }} install_recommends=yes state=latest"
    with_items:
    - python-obspy
    - python3-obspy

# Atlas setup
- hosts: compute
  become: yes
  gather_facts: no
  tags: atlas

  tasks:
  - name: 'install atlas'
    tags: update
    apt: "name={{ item }} install_recommends=yes state=latest"
    with_items:
    - libatlas3-base
    - liblapack-dev
  # file: src=/file/to/link/to dest=/path/to/symlink
  - name: 'configure atlas installation symlinks'
    file: src=/usr/lib/{{ item.src }} dest=/usr/lib/{{ item.dest }} state=link
    with_items:
    - { src: 'libatlas.so.3',   dest: 'libatlas.so' }
    - { src: 'libcblas.so.3',   dest: 'libcblas.so' }
    - { src: 'libf77blas.so.3', dest: 'libf77blas.so' }

# OpenAxiom
- hosts: compute
  become: yes
  gather_facts: yes
  tags: openaxiom
  ignore_errors: yes

  tasks:
  - name: "pippijn ppa repository apt key -- https://launchpad.net/~pippijn/+archive/ubuntu/ppa"
    apt_key: keyserver=keyserver.ubuntu.com id=D2D8EDD2BA10D39D925BB7ED11CA9C2FE368B17C
  - name: "pippijn ppa for open axiom apt repository (for precise, since xenial does not exist)"
    apt_repository: mode=644 repo='deb http://ppa.launchpad.net/pippijn/ppa/ubuntu precise main'
  - name: "install open axiom"
    tags: update
    apt: name="open-axiom*"
         install_recommends=yes
         state=latest

# Octave
- hosts: compute
  become: yes
  gather_facts: no
  tags: octave

  tasks:
  - name: "install ocatave"
    tags: update
    apt: "name={{ item }} install_recommends=yes state=latest"
    with_items:
    - octave-biosig
    - octave-common
    - octave-communications
    - octave-communications-common
    - octave-control
    - octave-data-smoothing
    - octave-dataframe
    - octave-dbg
    - octave-doc
    - octave-econometrics
    - octave-epstk
    - octave-financial
    - octave-fpl
    - octave-ga
    - octave-gdf
    - octave-general
    - octave-geometry
    - octave-gsl
    - octave-htmldoc
    - octave-image
    - octave-info
    - octave-io
    - octave-lhapdf
    - octave-linear-algebra
    - octave-miscellaneous
    - octave-missing-functions
    - octave-mpi
    - octave-nan
    - octave-nlopt
    - octave-nurbs
    - octave-ocs
    - octave-octcdf
    - octave-odepkg
    - octave-optim
    - octave-optiminterp
    - octave-parallel
    - octave-pfstools
    - octave-pkg-dev
    - octave-psychtoolbox-3
    - octave-quaternion
    - octave-secs2d
    - octave-signal
    - octave-sockets
    - octave-specfun
    - octave-splines
    - octave-statistics
    - octave-strings
    - octave-struct
    - octave-sundials
    - octave-symbolic
    - octave-tsa
    - octave-vlfeat
    - octave-vrml
    - octave-zenity
  - name: "fix some font for octave"
    file: src=/usr/share/fonts/truetype/liberation dest=/usr/share/fonts/truetype/ttf-liberation state=link
