---
- hosts: compute
  become: no
  gather_facts: yes
  strategy: free

  tasks:
  - name: "get metrics-* filenames"
    shell: ls -1 /home/salvus/logs/metrics-*.log*
    register: benchmark_filenames

  - name: "delete benchmark files"
    file: dest={{ item }}
          state=absent
    with_items: benchmark_filenames.stdout_lines
