---
# install the julia programming language from the ubuntu PPA on all compute nodes
# https://launchpad.net/~staticfloat/+archive/ubuntu/juliareleases
# https://launchpad.net/~staticfloat/+archive/ubuntu/julia-deps

- hosts: compute
  become: yes
  tags: julia
  gather_facts: no # set it to yes, if you need to use {{ ansible_distribution_release }} to know if it is vivid etc.

  tasks:

  - name: "julia ppa"
    apt_repository: repo='ppa:staticfloat/juliareleases'

  - name: "julia dependencies ppa"
    apt_repository: repo='ppa:staticfloat/julia-deps'

  - name: "apt-get install packages"
    apt: name={{ item }} install_recommends=yes state=latest
    with_items:
       - julia
       - julia-doc

  - name: "fix libzmq version #1 -- see build.md for what is going on here"
    apt: name=libzmq1 state=absent

  # in ubuntu xenial, that lib name or path changed
  #- name: "fix libzmq version #2"
  #  file: src=/usr/lib/x86_64-linux-gnu/libzmq.so.3 path=/usr/lib/x86_64-linux-gnu/libzmq.so state=link

  - name: "fix libzmq version #3 -- prevent apt from installing it again"
    shell: "echo 'Package: libzmq1\nPin: origin \"\"\nPin-Priority: -1' > /etc/apt/preferences"

  - name: "install some julia packages -- http://pkg.julialang.org/pulse.html"
    shell: "umask 022; export JULIA_PKGDIR=/usr/local/share/julia/site/; echo 'Pkg.add(\"{{ item }}\")' | julia; echo 'using {{ item }}' | julia"
    tags: install
    with_items:
    - PyCall # https://github.com/stevengj/PyCall.jl
    - IJulia # in jupyter notebook
    - Interact # https://github.com/JuliaLang/Interact.jl (for IJulia)
    - PyPlot # https://github.com/stevengj/PyPlot.jl
    - Bokeh  # https://github.com/JuliaLang/IJulia.jl
    - Gadfly # https://github.com/dcjones/Gadfly.jl
    - Mocha  # https://github.com/pluskid/Mocha.jl
    - DataFrames # https://github.com/JuliaStats/DataFrames.jl
    - Winston    # 2D plotting
    - Convex # https://github.com/JuliaOpt/Convex.jl (optimization)
    - Optim # https://github.com/JuliaOpt/Optim.jl
    - JuMP # https://github.com/JuliaOpt/JuMP.jl
    - ParallelAccelerator # https://github.com/IntelLabs/ParallelAccelerator.jl
    - MXNet # https://github.com/dmlc/MXNet.jl
    - Graphs # https://github.com/JuliaLang/Graphs.jl
    - Bio # https://github.com/BioJulia/Bio.jl (bioinformatics)
    - SCS # Solving optimization problems

  - name: "update julia packages"
    tags: update
    shell: "umask 022; echo 'Pkg.update()' | julia"

# Nemo (right after Julia!)
- hosts: compute
  become: yes
  gather_facts: no
  tags: nemo

  tasks:
  - name: "install nemo into julia (after julia has been installed)"
    shell: |
        umask 022
        export JULIA_PKGDIR=/usr/local/share/julia/site/
        echo 'Pkg.init()' | julia
        echo 'Pkg.clone("https://github.com/wbhart/Nemo.jl")' | julia
        echo 'Pkg.build("Nemo")' | julia
        export LD_LIBRARY_PATH=/usr/local/share/julia/site/v0.4/Nemo/local/lib
        cd $LD_LIBRARY_PATH
        ln -s libarb.so.0.0.0 libarb.so
        echo 'using Nemo' | julia
