---
# setting up global bashrc file for SMC banner and configs
- hosts: compute
  become: yes
  gather_facts: no
  strategy: free

  tasks:

  - name: "start bash.bashrc with TERM=screen (bug in vim?)"
    lineinfile: dest=/etc/bash.bashrc
                state=present
                insertbefore=BOF
                line: "TERM=screen"

  - name: "install the terminal-setup.sh file as /etc/bash-smc.bashrc"
    template: src=files/terminal-setup.sh
              dest=/etc/bash-smc.bashrc
              owner=root group=root mode="u=r,g=r,o=r"

  - name: "run this file from bash.bashrc, too (for interactive non-login shells)"
    lineinfile: dest=/etc/bash.bashrc
                state=present
                regexp='.*/etc/bash-smc.bashrc*'
                line='[ -r /etc/bash-smc.bashrc ] && . /etc/bash-smc.bashrc'
