/*
THE SECRET TOKEN

There is a column secret_token in the postgresql projects table.  That token is
generated by the server and must be made available by the hub to the project at startup,
so the hubs can connect to the project.   It is also used internally to secure some
communications.  The secret token must be written
to a file whose path is either $COCALC_SECRET_TOKEN *or* $DATA/secret-token.

In test mode, the token is not loaded from disk, since tests typically do not
set up the secret token file.
*/

import { readFileSync } from "fs";
import { getLogger } from "./logger";
import { join } from "path";
import { data } from "@cocalc/backend/data";

const logger = getLogger("data");

export let secretToken: string = "";

function init() {
  if (process.env.COCALC_TEST_MODE) {
    // test mode -- leave blank
    return;
  }
  // read from file
  logger.debug(`COCALC_SECRET_TOKEN = ${process.env.COCALC_SECRET_TOKEN}`);
  const secretTokenPath =
    process.env.COCALC_SECRET_TOKEN ?? join(data, "secret-token");
  try {
    secretToken = readFileSync(secretTokenPath).toString();
  } catch {
    // no file
    return;
  }
  logger.debug("Successfully initialized project secret_token");
}

init();
