###
Share server

ENDPOINTS:

- /alive - that this is working, database is responding, etc.
- raw   - raw unmodified static browser through all shared files in all projects
- share - browser through all shared files in all projects, but where pages are generated by backend server

###

exports.raw_router   = require('./raw').raw_router
exports.share_router = require('./share').share_router
exports.init = require('./dev').init
