/*
 *  This file is part of CoCalc: Copyright © 2020 Sagemath, Inc.
 *  License: AGPLv3 s.t. "Commons Clause" – see LICENSE.md for details
 */

/*
Share server

ENDPOINTS:

The share router:
    - /alive - that this is working, database is responding, etc.
    - /share/... - browser through all shared files in all projects, but where pages are generated by backend server
    - catches anything with a specified vhost in public_paths

*/

import * as share from "./share";
export const { share_router } = share;

import * as http_server from "./http-server";
export const { init } = http_server;
