import { Space } from "antd";
import Loading from "components/share/loading";
import register from "../register";
import useEditTable from "lib/hooks/edit-table";

interface Data {
  other_settings: {
    page_size: number;
  };
}

const desc = {
  page_size: `
Maximum number of files to show before a pager appears.  You can
keep this number pretty larger, because CoCalc uses an efficient
algorithm for scrolling through a large number of directory entries.
`,
  mask_files: `
Often there are files in a directory listing that are not hidden
(they do not start with a dot), but you also do not want to open them
since they are autogenerated and not human readable.  If you select
this option, by default such files still appear in the directory listing, but
in light grey, so they are less distracting.
`
};

register({
  path: "system/listings",
  title: "Listings",
  icon: "align-left",
  desc: "Directory listings",
  search: desc,
  Component: () => {
    const { edited, original, Save, EditBoolean, EditNumber } =
      useEditTable<Data>({
        accounts: { other_settings: null },
      });

    if (original == null || edited == null) {
      return <Loading />;
    }

    return (
      <Space direction="vertical" style={{ width: "100%" }}>
        <Save />
        <EditNumber
          path="other_settings.page_size"
          title="Number of files per page"
          icon="copy"
          desc={desc.page_size}
          min={1}
          max={10000}
          units="files"
        />
        <EditBoolean
          icon="mask"
          path="other_settings.mask_files"
          title="Mask Files"
          desc={desc.mask_files}
          label="Grey out files in directory listings that you probably do not want to open"
        />
      </Space>
    );
  },
});
