/*
 *  This file is part of CoCalc: Copyright © 2020 Sagemath, Inc.
 *  License: AGPLv3 s.t. "Commons Clause" – see LICENSE.md for details
 */

// Temporary work in progress for developing new ipywidgets integration.

import { createWidgetManager, WidgetEnvironment, IComm } from "@cocalc/widgets";

const f = () => {
  class Environment implements WidgetEnvironment {
    private state: object;
    constructor(state) {
      this.state = state;
    }

    async getModelState(modelId) {
      const state = this.state[modelId];
      state.modelName = state.state._model_name ?? state.model_name;
      state.modelModule = state.state._model_module ?? state.model_module;
      state.modelModuleVersion =
        state.state._model_module_version ?? state.model_module_version;
      return state;
    }

    openCommChannel(
      targetName: string,
      data?: unknown,
      buffers?: ArrayBuffer[],
    ): Promise<IComm> {
      console.log({ targetName, data, buffers });
      throw Error("not implemented");
    }

    renderOutput(outputItem: unknown, destination: Element): Promise<void> {
      console.log({ outputItem, destination });
      throw Error("not implemented");
    }
  }

  const leaflet = "34baf5762f2344e19200892a8efafc27";
  const three = "pythree_example_model_007";

  const provider = new Environment(getState());
  const manager = createWidgetManager(provider);
  return { provider, manager, leaflet, three };
};

function getState() {
  return {
    pythree_example_model_001: {
      model_module: "jupyter-threejs",
      model_module_version: "^2.1.0",
      model_name: "SphereGeometryModel",
      state: {
        _view_module: null,
        _view_module_version: "",
      },
    },
    pythree_example_model_002: {
      model_module: "jupyter-threejs",
      model_module_version: "^2.1.0",
      model_name: "MeshBasicMaterialModel",
      state: {
        _view_module: null,
        _view_module_version: "",
        color: "blue",
      },
    },
    pythree_example_model_003: {
      model_module: "jupyter-threejs",
      model_module_version: "^2.1.0",
      model_name: "MeshModel",
      state: {
        _view_module: null,
        _view_module_version: "",
        geometry: "IPY_MODEL_pythree_example_model_001",
        material: "IPY_MODEL_pythree_example_model_002",
        morphTargetInfluences: [],
      },
    },
    pythree_example_model_004: {
      model_module: "jupyter-threejs",
      model_module_version: "^2.1.0",
      model_name: "PerspectiveCameraModel",
      state: {
        _view_module: null,
        _view_module_version: "",
        matrix: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 5, 5, 1],
        position: [0, 5, 5],
        projectionMatrix: [
          2.1445069205095586, 0, 0, 0, 0, 2.1445069205095586, 0, 0, 0, 0,
          -1.00010000500025, -1, 0, 0, -0.200010000500025, 0,
        ],
      },
    },
    pythree_example_model_005: {
      model_module: "jupyter-threejs",
      model_module_version: "^2.1.0",
      model_name: "SceneModel",
      state: {
        _view_module: null,
        _view_module_version: "",
        background: "orange",
        children: [
          "IPY_MODEL_pythree_example_model_003",
          "IPY_MODEL_pythree_example_model_004",
        ],
      },
    },
    pythree_example_model_006: {
      model_module: "jupyter-threejs",
      model_module_version: "^2.1.0",
      model_name: "OrbitControlsModel",
      state: {
        _view_module: null,
        _view_module_version: "",
        controlling: "IPY_MODEL_pythree_example_model_004",
        maxAzimuthAngle: "inf",
        maxDistance: "inf",
        maxZoom: "inf",
        minAzimuthAngle: "-inf",
      },
    },
    pythree_example_model_007: {
      model_module: "jupyter-threejs",
      model_module_version: "^2.1.0",
      model_name: "RendererModel",
      state: {
        _alpha: true,
        _webgl_version: 2,
        camera: "IPY_MODEL_pythree_example_model_004",
        clearOpacity: 0,
        controls: ["IPY_MODEL_pythree_example_model_006"],
        layout: "IPY_MODEL_pythree_example_model_008",
        scene: "IPY_MODEL_pythree_example_model_005",
        shadowMap: "IPY_MODEL_pythree_example_model_009",
      },
    },
    pythree_example_model_008: {
      model_module: "@jupyter-widgets/base",
      model_module_version: "1.2.0",
      model_name: "LayoutModel",
      state: {},
    },
    pythree_example_model_009: {
      model_module: "jupyter-threejs",
      model_module_version: "^2.1.0",
      model_name: "WebGLShadowMapModel",
      state: {
        _view_module: null,
        _view_module_version: "",
      },
    },
    faa0370943904adaba3a65c9a9c28e7f: {
      model_module: "jupyter-leaflet",
      model_name: "LeafletMapModel",
      state: {
        _view_name: "LeafletMapView",
        keyboard_pan_offset: 80,
        tap: true,
        _view_module: "jupyter-leaflet",
        max_zoom: 18,
        _model_module_version: "^0.12.4",
        _view_count: null,
        min_zoom: 1,
        bounce_at_zoom_limits: true,
        keyboard: true,
        north: 0,
        scroll_wheel_zoom: false,
        dragging: true,
        _model_module: "jupyter-leaflet",
        close_popup_on_click: true,
        fullscreen: false,
        style: "IPY_MODEL_528f0499f48743a8aab05cdb29963956",
        layout: "IPY_MODEL_9d1e18a63d5847c09f65b5097436fb0b",
        inertia_max_speed: 1500,
        box_zoom: true,
        controls: [
          "IPY_MODEL_9e689d988abd486a8b09158c9e10dc07",
          "IPY_MODEL_8d48de7f99604d6da0bc2fa54dba2e6e",
        ],
        default_style: "IPY_MODEL_9ee3b8a2c715462688e02c8486b29d64",
        east: 0,
        double_click_zoom: true,
        interpolation: "bilinear",
        layers: ["IPY_MODEL_5ac6b3bdcfeb4ed8ba4769577a1cb943"],
        dragging_style: "IPY_MODEL_8a215f04298e4f0aa56d3e8ed2581d3d",
        _dom_classes: [],
        zoom_animation_threshold: 4,
        _model_name: "LeafletMapModel",
        zoom_start: 12,
        modisdate: "yesterday",
        keyboard_zoom_offset: 1,
        inertia_deceleration: 3000,
        inertia: true,
        crs: "EPSG3857",
        center: [52.204793, 360.121558],
        zoom: 4,
        world_copy_jump: false,
        _view_module_version: "^0.12.4",
        tap_tolerance: 15,
        west: 0,
        touch_zoom: true,
        options: [
          "bounce_at_zoom_limits",
          "box_zoom",
          "center",
          "close_popup_on_click",
          "double_click_zoom",
          "dragging",
          "fullscreen",
          "inertia",
          "inertia_deceleration",
          "inertia_max_speed",
          "interpolation",
          "keyboard",
          "keyboard_pan_offset",
          "keyboard_zoom_offset",
          "max_zoom",
          "min_zoom",
          "scroll_wheel_zoom",
          "tap",
          "tap_tolerance",
          "touch_zoom",
          "world_copy_jump",
          "zoom",
          "zoom_animation_threshold",
          "zoom_start",
        ],
        south: 0,
      },
    },
    "9d1e18a63d5847c09f65b5097436fb0b": {
      model_module: "@jupyter-widgets/base",
      model_name: "LayoutModel",
      state: {
        _view_name: "LayoutView",
        grid_template_rows: null,
        right: null,
        justify_content: null,
        _view_module: "@jupyter-widgets/base",
        overflow: null,
        _model_module_version: "1.2.0",
        _view_count: null,
        flex_flow: null,
        width: null,
        min_width: null,
        border: null,
        align_items: null,
        bottom: null,
        _model_module: "@jupyter-widgets/base",
        top: null,
        grid_column: null,
        overflow_y: null,
        overflow_x: null,
        grid_auto_flow: null,
        grid_area: null,
        grid_template_columns: null,
        flex: null,
        _model_name: "LayoutModel",
        justify_items: null,
        grid_row: null,
        max_height: null,
        align_content: null,
        visibility: null,
        align_self: null,
        height: null,
        min_height: null,
        padding: null,
        grid_auto_rows: null,
        grid_gap: null,
        max_width: null,
        order: null,
        _view_module_version: "1.2.0",
        grid_template_areas: null,
        object_position: null,
        object_fit: null,
        grid_auto_columns: null,
        margin: null,
        display: null,
        left: null,
      },
    },
    ed8b79e7b266419981ca163a39b8e84d: {
      model_module: "@jupyter-widgets/controls",
      model_name: "VBoxModel",
      state: {
        _view_name: "VBoxView",
        _dom_classes: [],
        _model_name: "VBoxModel",
        _view_module: "@jupyter-widgets/controls",
        _model_module_version: "1.5.0",
        _view_count: null,
        _view_module_version: "1.5.0",
        box_style: "",
        layout: "IPY_MODEL_cfa51ae0b686483d9e6af5ded299e797",
        _model_module: "@jupyter-widgets/controls",
        children: [
          "IPY_MODEL_365a9442d01e4385b873e1dfe52feb70",
          "IPY_MODEL_9447dbf2ceda462f8935eab8b617bfae",
          "IPY_MODEL_7477689a59354b559db709132bbf7ebc",
        ],
      },
    },
    cfa51ae0b686483d9e6af5ded299e797: {
      model_module: "@jupyter-widgets/base",
      model_name: "LayoutModel",
      state: {
        _view_name: "LayoutView",
        grid_template_rows: null,
        right: null,
        justify_content: null,
        _view_module: "@jupyter-widgets/base",
        overflow: null,
        _model_module_version: "1.2.0",
        _view_count: null,
        flex_flow: null,
        width: null,
        min_width: null,
        border: null,
        align_items: null,
        bottom: null,
        _model_module: "@jupyter-widgets/base",
        top: null,
        grid_column: null,
        overflow_y: null,
        overflow_x: null,
        grid_auto_flow: null,
        grid_area: null,
        grid_template_columns: null,
        flex: null,
        _model_name: "LayoutModel",
        justify_items: null,
        grid_row: null,
        max_height: null,
        align_content: null,
        visibility: null,
        align_self: null,
        height: null,
        min_height: null,
        padding: null,
        grid_auto_rows: null,
        grid_gap: null,
        max_width: null,
        order: null,
        _view_module_version: "1.2.0",
        grid_template_areas: null,
        object_position: null,
        object_fit: null,
        grid_auto_columns: null,
        margin: null,
        display: null,
        left: null,
      },
    },
    "365a9442d01e4385b873e1dfe52feb70": {
      model_module: "@jupyter-widgets/controls",
      model_name: "VBoxModel",
      state: {
        _view_name: "VBoxView",
        _dom_classes: [],
        _model_name: "VBoxModel",
        _view_module: "@jupyter-widgets/controls",
        _model_module_version: "1.5.0",
        _view_count: null,
        _view_module_version: "1.5.0",
        box_style: "",
        layout: "IPY_MODEL_100eb6ce562243cc8d5b70aad0f59f58",
        _model_module: "@jupyter-widgets/controls",
        children: [
          "IPY_MODEL_19b20aa775cf428883c2e7dfd5cc3bd0",
          "IPY_MODEL_4b54c82f7c7049049030ed6a426871dc",
        ],
      },
    },
    "9447dbf2ceda462f8935eab8b617bfae": {
      model_module: "ipyvolume",
      model_name: "FigureModel",
      state: {
        _view_name: "FigureView",
        xlim: [0, 128],
        show: "Volume",
        camera_control: "trackball",
        _view_module: "ipyvolume",
        ambient_coefficient: 0.5,
        _view_count: null,
        style: {
          box: {
            visible: true,
          },
          axes: {
            color: "black",
            visible: true,
            ticklabel: {
              color: "black",
            },
            label: {
              color: "black",
            },
          },
          "background-color": "white",
        },
        meshes: [],
        matrix_world: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        _model_module: "ipyvolume",
        ylim: [0, 128],
        animation_exponent: 1,
        layout: "IPY_MODEL_af8f54e0b1644171a2ef24959367b58a",
        camera_fov: 45,
        specular_exponent: 5,
        render_continuous: false,
        panorama_mode: "no",
        width: 400,
        camera: "IPY_MODEL_866ab03c46e440f7801230d57716869b",
        diffuse_coefficient: 0.8,
        zlabel: "z",
        capture_fps: null,
        downscale: 1,
        _dom_classes: [],
        _model_name: "FigureModel",
        selection_mode: "replace",
        ylabel: "y",
        matrix_projection: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        stereo: false,
        _model_module_version: "~0.5.2",
        specular_coefficient: 0.5,
        height: 500,
        animation: 1000,
        eye_separation: 6.4,
        selector: "lasso",
        scene: "IPY_MODEL_68f6502f5a3b46e294f8ed64c4ded169",
        zlim: [0, 128],
        camera_center: [0, 0, 0],
        scatters: [],
        _view_module_version: "~0.5.2",
        xlabel: "x",
        volumes: ["IPY_MODEL_92610383004a4f27af081962e62d46f8"],
        displayscale: 1,
        cube_resolution: 512,
        mouse_mode: "normal",
      },
    },
    "7477689a59354b559db709132bbf7ebc": {
      model_module: "@jupyter-widgets/controls",
      model_name: "HBoxModel",
      state: {
        _view_name: "HBoxView",
        _dom_classes: [],
        _model_name: "HBoxModel",
        _view_module: "@jupyter-widgets/controls",
        _model_module_version: "1.5.0",
        _view_count: null,
        _view_module_version: "1.5.0",
        box_style: "",
        layout: "IPY_MODEL_488d6d91b19e4cb7bb78d107f141db56",
        _model_module: "@jupyter-widgets/controls",
        children: [
          "IPY_MODEL_97dbb363ff564cceb42e2ccb4a4950ff",
          "IPY_MODEL_b8f9849acedc46228ddd4d6acdb22e22",
        ],
      },
    },
    "100eb6ce562243cc8d5b70aad0f59f58": {
      model_module: "@jupyter-widgets/base",
      model_name: "LayoutModel",
      state: {
        _view_name: "LayoutView",
        grid_template_rows: null,
        right: null,
        justify_content: null,
        _view_module: "@jupyter-widgets/base",
        overflow: null,
        _model_module_version: "1.2.0",
        _view_count: null,
        flex_flow: null,
        width: null,
        min_width: null,
        border: null,
        align_items: null,
        bottom: null,
        _model_module: "@jupyter-widgets/base",
        top: null,
        grid_column: null,
        overflow_y: null,
        overflow_x: null,
        grid_auto_flow: null,
        grid_area: null,
        grid_template_columns: null,
        flex: null,
        _model_name: "LayoutModel",
        justify_items: null,
        grid_row: null,
        max_height: null,
        align_content: null,
        visibility: null,
        align_self: null,
        height: null,
        min_height: null,
        padding: null,
        grid_auto_rows: null,
        grid_gap: null,
        max_width: null,
        order: null,
        _view_module_version: "1.2.0",
        grid_template_areas: null,
        object_position: null,
        object_fit: null,
        grid_auto_columns: null,
        margin: null,
        display: null,
        left: null,
      },
    },
    "19b20aa775cf428883c2e7dfd5cc3bd0": {
      model_module: "@jupyter-widgets/controls",
      model_name: "HBoxModel",
      state: {
        _view_name: "HBoxView",
        _dom_classes: [],
        _model_name: "HBoxModel",
        _view_module: "@jupyter-widgets/controls",
        _model_module_version: "1.5.0",
        _view_count: null,
        _view_module_version: "1.5.0",
        box_style: "",
        layout: "IPY_MODEL_f0dc675ecb5f4325ae48ca250e29cd5e",
        _model_module: "@jupyter-widgets/controls",
        children: [
          "IPY_MODEL_02d4eb26fb22419d96533c6679dae3a1",
          "IPY_MODEL_8c2d51efdcfa4427924009c0b0546c7c",
          "IPY_MODEL_cf4babd2876747ac8bd0c6f282d42edf",
          "IPY_MODEL_74d38f08eadb4fa49c7850dcbf94f133",
        ],
      },
    },
    "4b54c82f7c7049049030ed6a426871dc": {
      model_module: "@jupyter-widgets/controls",
      model_name: "HBoxModel",
      state: {
        _view_name: "HBoxView",
        _dom_classes: [],
        _model_name: "HBoxModel",
        _view_module: "@jupyter-widgets/controls",
        _model_module_version: "1.5.0",
        _view_count: null,
        _view_module_version: "1.5.0",
        box_style: "",
        layout: "IPY_MODEL_f69e48b53b7c46f498c4bface2dd01e8",
        _model_module: "@jupyter-widgets/controls",
        children: [
          "IPY_MODEL_a9cbe234131c45b1a281c4db15e99413",
          "IPY_MODEL_78a5d136a1f64174845163009a758048",
          "IPY_MODEL_4388082b3f5a4f7499c7a64c69683430",
          "IPY_MODEL_34e05629fda64857b27a55a6fb3966ff",
        ],
      },
    },
    "488d6d91b19e4cb7bb78d107f141db56": {
      model_module: "@jupyter-widgets/base",
      model_name: "LayoutModel",
      state: {
        _view_name: "LayoutView",
        grid_template_rows: null,
        right: null,
        justify_content: null,
        _view_module: "@jupyter-widgets/base",
        overflow: null,
        _model_module_version: "1.2.0",
        _view_count: null,
        flex_flow: null,
        width: null,
        min_width: null,
        border: null,
        align_items: null,
        bottom: null,
        _model_module: "@jupyter-widgets/base",
        top: null,
        grid_column: null,
        overflow_y: null,
        overflow_x: null,
        grid_auto_flow: null,
        grid_area: null,
        grid_template_columns: null,
        flex: null,
        _model_name: "LayoutModel",
        justify_items: null,
        grid_row: null,
        max_height: null,
        align_content: null,
        visibility: null,
        align_self: null,
        height: null,
        min_height: null,
        padding: null,
        grid_auto_rows: null,
        grid_gap: null,
        max_width: null,
        order: null,
        _view_module_version: "1.2.0",
        grid_template_areas: null,
        object_position: null,
        object_fit: null,
        grid_auto_columns: null,
        margin: null,
        display: null,
        left: null,
      },
    },
    "97dbb363ff564cceb42e2ccb4a4950ff": {
      model_module: "@jupyter-widgets/controls",
      model_name: "FloatLogSliderModel",
      state: {
        _view_name: "FloatLogSliderView",
        orientation: "horizontal",
        _view_module: "@jupyter-widgets/controls",
        _model_module_version: "1.5.0",
        _view_count: null,
        disabled: false,
        readout_format: ".3g",
        _model_module: "@jupyter-widgets/controls",
        style: "IPY_MODEL_4f3473b3f5cc4f62a610db6c40461dd4",
        layout: "IPY_MODEL_8ed0972e56764df4ad5ca6e335a0e0c0",
        min: -2,
        continuous_update: true,
        description_tooltip: null,
        _dom_classes: [],
        description: "opacity",
        _model_name: "FloatLogSliderModel",
        max: 2,
        readout: true,
        step: 0.1,
        base: 10,
        value: 1,
        _view_module_version: "1.5.0",
      },
    },
    b8f9849acedc46228ddd4d6acdb22e22: {
      model_module: "@jupyter-widgets/controls",
      model_name: "FloatLogSliderModel",
      state: {
        _view_name: "FloatLogSliderView",
        orientation: "horizontal",
        _view_module: "@jupyter-widgets/controls",
        _model_module_version: "1.5.0",
        _view_count: null,
        disabled: false,
        readout_format: ".3g",
        _model_module: "@jupyter-widgets/controls",
        style: "IPY_MODEL_bbb62806ad2c450ba5b0e471ef86fdb3",
        layout: "IPY_MODEL_a79ca8a3ba1a4c128ed076a55e7d26d3",
        min: -1,
        continuous_update: true,
        description_tooltip: null,
        _dom_classes: [],
        description: "brightness",
        _model_name: "FloatLogSliderModel",
        max: 1,
        readout: true,
        step: 0.1,
        base: 10,
        value: 1,
        _view_module_version: "1.5.0",
      },
    },
    f0dc675ecb5f4325ae48ca250e29cd5e: {
      model_module: "@jupyter-widgets/base",
      model_name: "LayoutModel",
      state: {
        _view_name: "LayoutView",
        grid_template_rows: null,
        right: null,
        justify_content: null,
        _view_module: "@jupyter-widgets/base",
        overflow: null,
        _model_module_version: "1.2.0",
        _view_count: null,
        flex_flow: null,
        width: null,
        min_width: null,
        border: null,
        align_items: null,
        bottom: null,
        _model_module: "@jupyter-widgets/base",
        top: null,
        grid_column: null,
        overflow_y: null,
        overflow_x: null,
        grid_auto_flow: null,
        grid_area: null,
        grid_template_columns: null,
        flex: null,
        _model_name: "LayoutModel",
        justify_items: null,
        grid_row: null,
        max_height: null,
        align_content: null,
        visibility: null,
        align_self: null,
        height: null,
        min_height: null,
        padding: null,
        grid_auto_rows: null,
        grid_gap: null,
        max_width: null,
        order: null,
        _view_module_version: "1.2.0",
        grid_template_areas: null,
        object_position: null,
        object_fit: null,
        grid_auto_columns: null,
        margin: null,
        display: null,
        left: null,
      },
    },
    "02d4eb26fb22419d96533c6679dae3a1": {
      model_module: "@jupyter-widgets/controls",
      model_name: "LabelModel",
      state: {
        _view_name: "LabelView",
        style: "IPY_MODEL_60b66f00eb1e459d9d1384ed36238097",
        _dom_classes: [],
        description: "",
        _model_name: "LabelModel",
        placeholder: "​",
        _view_module: "@jupyter-widgets/controls",
        _model_module_version: "1.5.0",
        value: "levels:",
        _view_count: null,
        _view_module_version: "1.5.0",
        description_tooltip: null,
        _model_module: "@jupyter-widgets/controls",
        layout: "IPY_MODEL_e6ca23c5433d4cdb9160d74970d7afcc",
      },
    },
    "8c2d51efdcfa4427924009c0b0546c7c": {
      model_module: "@jupyter-widgets/controls",
      model_name: "FloatSliderModel",
      state: {
        _view_name: "FloatSliderView",
        style: "IPY_MODEL_2b7ee84a8e7f49bfbd1326008de861b8",
        _dom_classes: [],
        description: "",
        step: 0.001,
        _model_name: "FloatSliderModel",
        orientation: "horizontal",
        max: 1,
        _view_module: "@jupyter-widgets/controls",
        _model_module_version: "1.5.0",
        value: 0.25,
        _view_count: null,
        disabled: false,
        _view_module_version: "1.5.0",
        min: 0,
        continuous_update: true,
        readout_format: ".2f",
        description_tooltip: null,
        readout: true,
        _model_module: "@jupyter-widgets/controls",
        layout: "IPY_MODEL_39689dcb46a84e1499b45103b73b313a",
      },
    },
    cf4babd2876747ac8bd0c6f282d42edf: {
      model_module: "@jupyter-widgets/controls",
      model_name: "FloatSliderModel",
      state: {
        _view_name: "FloatSliderView",
        style: "IPY_MODEL_2989acf9d262489f9f038294eb506507",
        _dom_classes: [],
        description: "",
        step: 0.001,
        _model_name: "FloatSliderModel",
        orientation: "horizontal",
        max: 1,
        _view_module: "@jupyter-widgets/controls",
        _model_module_version: "1.5.0",
        value: 0.75,
        _view_count: null,
        disabled: false,
        _view_module_version: "1.5.0",
        min: 0,
        continuous_update: true,
        readout_format: ".2f",
        description_tooltip: null,
        readout: true,
        _model_module: "@jupyter-widgets/controls",
        layout: "IPY_MODEL_a15e6cf4f5694dd8bd8b7673e0f3ac55",
      },
    },
    "74d38f08eadb4fa49c7850dcbf94f133": {
      model_module: "@jupyter-widgets/controls",
      model_name: "FloatSliderModel",
      state: {
        _view_name: "FloatSliderView",
        style: "IPY_MODEL_73e2d14fea6d449d878803d1a08d2956",
        _dom_classes: [],
        description: "",
        step: 0.001,
        _model_name: "FloatSliderModel",
        orientation: "horizontal",
        max: 1,
        _view_module: "@jupyter-widgets/controls",
        _model_module_version: "1.5.0",
        value: 0,
        _view_count: null,
        disabled: false,
        _view_module_version: "1.5.0",
        min: 0,
        continuous_update: true,
        readout_format: ".2f",
        description_tooltip: null,
        readout: true,
        _model_module: "@jupyter-widgets/controls",
        layout: "IPY_MODEL_af00703ee841496e9acddae379137791",
      },
    },
    f69e48b53b7c46f498c4bface2dd01e8: {
      model_module: "@jupyter-widgets/base",
      model_name: "LayoutModel",
      state: {
        _view_name: "LayoutView",
        grid_template_rows: null,
        right: null,
        justify_content: null,
        _view_module: "@jupyter-widgets/base",
        overflow: null,
        _model_module_version: "1.2.0",
        _view_count: null,
        flex_flow: null,
        width: null,
        min_width: null,
        border: null,
        align_items: null,
        bottom: null,
        _model_module: "@jupyter-widgets/base",
        top: null,
        grid_column: null,
        overflow_y: null,
        overflow_x: null,
        grid_auto_flow: null,
        grid_area: null,
        grid_template_columns: null,
        flex: null,
        _model_name: "LayoutModel",
        justify_items: null,
        grid_row: null,
        max_height: null,
        align_content: null,
        visibility: null,
        align_self: null,
        height: null,
        min_height: null,
        padding: null,
        grid_auto_rows: null,
        grid_gap: null,
        max_width: null,
        order: null,
        _view_module_version: "1.2.0",
        grid_template_areas: null,
        object_position: null,
        object_fit: null,
        grid_auto_columns: null,
        margin: null,
        display: null,
        left: null,
      },
    },
    a9cbe234131c45b1a281c4db15e99413: {
      model_module: "@jupyter-widgets/controls",
      model_name: "LabelModel",
      state: {
        _view_name: "LabelView",
        style: "IPY_MODEL_767ef02d73824074b53829d92b0eccc5",
        _dom_classes: [],
        description: "",
        _model_name: "LabelModel",
        placeholder: "​",
        _view_module: "@jupyter-widgets/controls",
        _model_module_version: "1.5.0",
        value: "opacities:",
        _view_count: null,
        _view_module_version: "1.5.0",
        description_tooltip: null,
        _model_module: "@jupyter-widgets/controls",
        layout: "IPY_MODEL_f6d3348ed360411da83bb289fea09846",
      },
    },
    "78a5d136a1f64174845163009a758048": {
      model_module: "@jupyter-widgets/controls",
      model_name: "FloatSliderModel",
      state: {
        _view_name: "FloatSliderView",
        style: "IPY_MODEL_45a664907a2e4c388abdfdefd4b9377a",
        _dom_classes: [],
        description: "",
        step: 0.001,
        _model_name: "FloatSliderModel",
        orientation: "horizontal",
        max: 0.2,
        _view_module: "@jupyter-widgets/controls",
        _model_module_version: "1.5.0",
        value: 0.03,
        _view_count: null,
        disabled: false,
        _view_module_version: "1.5.0",
        min: 0,
        continuous_update: true,
        readout_format: ".2f",
        description_tooltip: null,
        readout: true,
        _model_module: "@jupyter-widgets/controls",
        layout: "IPY_MODEL_947e562976c449718578676a34739494",
      },
    },
    "4388082b3f5a4f7499c7a64c69683430": {
      model_module: "@jupyter-widgets/controls",
      model_name: "FloatSliderModel",
      state: {
        _view_name: "FloatSliderView",
        style: "IPY_MODEL_389cbfc5e0dd4bfd99a1881f0b408156",
        _dom_classes: [],
        description: "",
        step: 0.001,
        _model_name: "FloatSliderModel",
        orientation: "horizontal",
        max: 0.2,
        _view_module: "@jupyter-widgets/controls",
        _model_module_version: "1.5.0",
        value: 0.03,
        _view_count: null,
        disabled: false,
        _view_module_version: "1.5.0",
        min: 0,
        continuous_update: true,
        readout_format: ".2f",
        description_tooltip: null,
        readout: true,
        _model_module: "@jupyter-widgets/controls",
        layout: "IPY_MODEL_b44b6db482b04c55bf7345caa48419e7",
      },
    },
    "34e05629fda64857b27a55a6fb3966ff": {
      model_module: "@jupyter-widgets/controls",
      model_name: "FloatSliderModel",
      state: {
        _view_name: "FloatSliderView",
        style: "IPY_MODEL_bf0d78a072ca4ecd8ab2da9d609af582",
        _dom_classes: [],
        description: "",
        step: 0.001,
        _model_name: "FloatSliderModel",
        orientation: "horizontal",
        max: 0.2,
        _view_module: "@jupyter-widgets/controls",
        _model_module_version: "1.5.0",
        value: 0.03,
        _view_count: null,
        disabled: false,
        _view_module_version: "1.5.0",
        min: 0,
        continuous_update: true,
        readout_format: ".2f",
        description_tooltip: null,
        readout: true,
        _model_module: "@jupyter-widgets/controls",
        layout: "IPY_MODEL_454bb9c66647447bb5af1b8c0c44b089",
      },
    },
    "4f3473b3f5cc4f62a610db6c40461dd4": {
      model_module: "@jupyter-widgets/controls",
      model_name: "SliderStyleModel",
      state: {
        _view_name: "StyleView",
        handle_color: null,
        _model_name: "SliderStyleModel",
        description_width: "",
        _view_module: "@jupyter-widgets/base",
        _model_module_version: "1.5.0",
        _view_count: null,
        _view_module_version: "1.2.0",
        _model_module: "@jupyter-widgets/controls",
      },
    },
    "8ed0972e56764df4ad5ca6e335a0e0c0": {
      model_module: "@jupyter-widgets/base",
      model_name: "LayoutModel",
      state: {
        _view_name: "LayoutView",
        grid_template_rows: null,
        right: null,
        justify_content: null,
        _view_module: "@jupyter-widgets/base",
        overflow: null,
        _model_module_version: "1.2.0",
        _view_count: null,
        flex_flow: null,
        width: null,
        min_width: null,
        border: null,
        align_items: null,
        bottom: null,
        _model_module: "@jupyter-widgets/base",
        top: null,
        grid_column: null,
        overflow_y: null,
        overflow_x: null,
        grid_auto_flow: null,
        grid_area: null,
        grid_template_columns: null,
        flex: null,
        _model_name: "LayoutModel",
        justify_items: null,
        grid_row: null,
        max_height: null,
        align_content: null,
        visibility: null,
        align_self: null,
        height: null,
        min_height: null,
        padding: null,
        grid_auto_rows: null,
        grid_gap: null,
        max_width: null,
        order: null,
        _view_module_version: "1.2.0",
        grid_template_areas: null,
        object_position: null,
        object_fit: null,
        grid_auto_columns: null,
        margin: null,
        display: null,
        left: null,
      },
    },
    bbb62806ad2c450ba5b0e471ef86fdb3: {
      model_module: "@jupyter-widgets/controls",
      model_name: "SliderStyleModel",
      state: {
        _view_name: "StyleView",
        handle_color: null,
        _model_name: "SliderStyleModel",
        description_width: "",
        _view_module: "@jupyter-widgets/base",
        _model_module_version: "1.5.0",
        _view_count: null,
        _view_module_version: "1.2.0",
        _model_module: "@jupyter-widgets/controls",
      },
    },
    a79ca8a3ba1a4c128ed076a55e7d26d3: {
      model_module: "@jupyter-widgets/base",
      model_name: "LayoutModel",
      state: {
        _view_name: "LayoutView",
        grid_template_rows: null,
        right: null,
        justify_content: null,
        _view_module: "@jupyter-widgets/base",
        overflow: null,
        _model_module_version: "1.2.0",
        _view_count: null,
        flex_flow: null,
        width: null,
        min_width: null,
        border: null,
        align_items: null,
        bottom: null,
        _model_module: "@jupyter-widgets/base",
        top: null,
        grid_column: null,
        overflow_y: null,
        overflow_x: null,
        grid_auto_flow: null,
        grid_area: null,
        grid_template_columns: null,
        flex: null,
        _model_name: "LayoutModel",
        justify_items: null,
        grid_row: null,
        max_height: null,
        align_content: null,
        visibility: null,
        align_self: null,
        height: null,
        min_height: null,
        padding: null,
        grid_auto_rows: null,
        grid_gap: null,
        max_width: null,
        order: null,
        _view_module_version: "1.2.0",
        grid_template_areas: null,
        object_position: null,
        object_fit: null,
        grid_auto_columns: null,
        margin: null,
        display: null,
        left: null,
      },
    },
    "60b66f00eb1e459d9d1384ed36238097": {
      model_module: "@jupyter-widgets/controls",
      model_name: "DescriptionStyleModel",
      state: {
        _view_name: "StyleView",
        _model_name: "DescriptionStyleModel",
        description_width: "",
        _view_module: "@jupyter-widgets/base",
        _model_module_version: "1.5.0",
        _view_count: null,
        _view_module_version: "1.2.0",
        _model_module: "@jupyter-widgets/controls",
      },
    },
    e6ca23c5433d4cdb9160d74970d7afcc: {
      model_module: "@jupyter-widgets/base",
      model_name: "LayoutModel",
      state: {
        _view_name: "LayoutView",
        grid_template_rows: null,
        right: null,
        justify_content: null,
        _view_module: "@jupyter-widgets/base",
        overflow: null,
        _model_module_version: "1.2.0",
        _view_count: null,
        flex_flow: null,
        width: null,
        min_width: null,
        border: null,
        align_items: null,
        bottom: null,
        _model_module: "@jupyter-widgets/base",
        top: null,
        grid_column: null,
        overflow_y: null,
        overflow_x: null,
        grid_auto_flow: null,
        grid_area: null,
        grid_template_columns: null,
        flex: null,
        _model_name: "LayoutModel",
        justify_items: null,
        grid_row: null,
        max_height: null,
        align_content: null,
        visibility: null,
        align_self: null,
        height: null,
        min_height: null,
        padding: null,
        grid_auto_rows: null,
        grid_gap: null,
        max_width: null,
        order: null,
        _view_module_version: "1.2.0",
        grid_template_areas: null,
        object_position: null,
        object_fit: null,
        grid_auto_columns: null,
        margin: null,
        display: null,
        left: null,
      },
    },
    "2b7ee84a8e7f49bfbd1326008de861b8": {
      model_module: "@jupyter-widgets/controls",
      model_name: "SliderStyleModel",
      state: {
        _view_name: "StyleView",
        handle_color: null,
        _model_name: "SliderStyleModel",
        description_width: "",
        _view_module: "@jupyter-widgets/base",
        _model_module_version: "1.5.0",
        _view_count: null,
        _view_module_version: "1.2.0",
        _model_module: "@jupyter-widgets/controls",
      },
    },
    "39689dcb46a84e1499b45103b73b313a": {
      model_module: "@jupyter-widgets/base",
      model_name: "LayoutModel",
      state: {
        _view_name: "LayoutView",
        grid_template_rows: null,
        right: null,
        justify_content: null,
        _view_module: "@jupyter-widgets/base",
        overflow: null,
        _model_module_version: "1.2.0",
        _view_count: null,
        flex_flow: null,
        width: null,
        min_width: null,
        border: null,
        align_items: null,
        bottom: null,
        _model_module: "@jupyter-widgets/base",
        top: null,
        grid_column: null,
        overflow_y: null,
        overflow_x: null,
        grid_auto_flow: null,
        grid_area: null,
        grid_template_columns: null,
        flex: null,
        _model_name: "LayoutModel",
        justify_items: null,
        grid_row: null,
        max_height: null,
        align_content: null,
        visibility: null,
        align_self: null,
        height: null,
        min_height: null,
        padding: null,
        grid_auto_rows: null,
        grid_gap: null,
        max_width: null,
        order: null,
        _view_module_version: "1.2.0",
        grid_template_areas: null,
        object_position: null,
        object_fit: null,
        grid_auto_columns: null,
        margin: null,
        display: null,
        left: null,
      },
    },
    "2989acf9d262489f9f038294eb506507": {
      model_module: "@jupyter-widgets/controls",
      model_name: "SliderStyleModel",
      state: {
        _view_name: "StyleView",
        handle_color: null,
        _model_name: "SliderStyleModel",
        description_width: "",
        _view_module: "@jupyter-widgets/base",
        _model_module_version: "1.5.0",
        _view_count: null,
        _view_module_version: "1.2.0",
        _model_module: "@jupyter-widgets/controls",
      },
    },
    a15e6cf4f5694dd8bd8b7673e0f3ac55: {
      model_module: "@jupyter-widgets/base",
      model_name: "LayoutModel",
      state: {
        _view_name: "LayoutView",
        grid_template_rows: null,
        right: null,
        justify_content: null,
        _view_module: "@jupyter-widgets/base",
        overflow: null,
        _model_module_version: "1.2.0",
        _view_count: null,
        flex_flow: null,
        width: null,
        min_width: null,
        border: null,
        align_items: null,
        bottom: null,
        _model_module: "@jupyter-widgets/base",
        top: null,
        grid_column: null,
        overflow_y: null,
        overflow_x: null,
        grid_auto_flow: null,
        grid_area: null,
        grid_template_columns: null,
        flex: null,
        _model_name: "LayoutModel",
        justify_items: null,
        grid_row: null,
        max_height: null,
        align_content: null,
        visibility: null,
        align_self: null,
        height: null,
        min_height: null,
        padding: null,
        grid_auto_rows: null,
        grid_gap: null,
        max_width: null,
        order: null,
        _view_module_version: "1.2.0",
        grid_template_areas: null,
        object_position: null,
        object_fit: null,
        grid_auto_columns: null,
        margin: null,
        display: null,
        left: null,
      },
    },
    "73e2d14fea6d449d878803d1a08d2956": {
      model_module: "@jupyter-widgets/controls",
      model_name: "SliderStyleModel",
      state: {
        _view_name: "StyleView",
        handle_color: null,
        _model_name: "SliderStyleModel",
        description_width: "",
        _view_module: "@jupyter-widgets/base",
        _model_module_version: "1.5.0",
        _view_count: null,
        _view_module_version: "1.2.0",
        _model_module: "@jupyter-widgets/controls",
      },
    },
    af00703ee841496e9acddae379137791: {
      model_module: "@jupyter-widgets/base",
      model_name: "LayoutModel",
      state: {
        _view_name: "LayoutView",
        grid_template_rows: null,
        right: null,
        justify_content: null,
        _view_module: "@jupyter-widgets/base",
        overflow: null,
        _model_module_version: "1.2.0",
        _view_count: null,
        flex_flow: null,
        width: null,
        min_width: null,
        border: null,
        align_items: null,
        bottom: null,
        _model_module: "@jupyter-widgets/base",
        top: null,
        grid_column: null,
        overflow_y: null,
        overflow_x: null,
        grid_auto_flow: null,
        grid_area: null,
        grid_template_columns: null,
        flex: null,
        _model_name: "LayoutModel",
        justify_items: null,
        grid_row: null,
        max_height: null,
        align_content: null,
        visibility: null,
        align_self: null,
        height: null,
        min_height: null,
        padding: null,
        grid_auto_rows: null,
        grid_gap: null,
        max_width: null,
        order: null,
        _view_module_version: "1.2.0",
        grid_template_areas: null,
        object_position: null,
        object_fit: null,
        grid_auto_columns: null,
        margin: null,
        display: null,
        left: null,
      },
    },
    "767ef02d73824074b53829d92b0eccc5": {
      model_module: "@jupyter-widgets/controls",
      model_name: "DescriptionStyleModel",
      state: {
        _view_name: "StyleView",
        _model_name: "DescriptionStyleModel",
        description_width: "",
        _view_module: "@jupyter-widgets/base",
        _model_module_version: "1.5.0",
        _view_count: null,
        _view_module_version: "1.2.0",
        _model_module: "@jupyter-widgets/controls",
      },
    },
    f6d3348ed360411da83bb289fea09846: {
      model_module: "@jupyter-widgets/base",
      model_name: "LayoutModel",
      state: {
        _view_name: "LayoutView",
        grid_template_rows: null,
        right: null,
        justify_content: null,
        _view_module: "@jupyter-widgets/base",
        overflow: null,
        _model_module_version: "1.2.0",
        _view_count: null,
        flex_flow: null,
        width: null,
        min_width: null,
        border: null,
        align_items: null,
        bottom: null,
        _model_module: "@jupyter-widgets/base",
        top: null,
        grid_column: null,
        overflow_y: null,
        overflow_x: null,
        grid_auto_flow: null,
        grid_area: null,
        grid_template_columns: null,
        flex: null,
        _model_name: "LayoutModel",
        justify_items: null,
        grid_row: null,
        max_height: null,
        align_content: null,
        visibility: null,
        align_self: null,
        height: null,
        min_height: null,
        padding: null,
        grid_auto_rows: null,
        grid_gap: null,
        max_width: null,
        order: null,
        _view_module_version: "1.2.0",
        grid_template_areas: null,
        object_position: null,
        object_fit: null,
        grid_auto_columns: null,
        margin: null,
        display: null,
        left: null,
      },
    },
    "45a664907a2e4c388abdfdefd4b9377a": {
      model_module: "@jupyter-widgets/controls",
      model_name: "SliderStyleModel",
      state: {
        _view_name: "StyleView",
        handle_color: null,
        _model_name: "SliderStyleModel",
        description_width: "",
        _view_module: "@jupyter-widgets/base",
        _model_module_version: "1.5.0",
        _view_count: null,
        _view_module_version: "1.2.0",
        _model_module: "@jupyter-widgets/controls",
      },
    },
    "947e562976c449718578676a34739494": {
      model_module: "@jupyter-widgets/base",
      model_name: "LayoutModel",
      state: {
        _view_name: "LayoutView",
        grid_template_rows: null,
        right: null,
        justify_content: null,
        _view_module: "@jupyter-widgets/base",
        overflow: null,
        _model_module_version: "1.2.0",
        _view_count: null,
        flex_flow: null,
        width: null,
        min_width: null,
        border: null,
        align_items: null,
        bottom: null,
        _model_module: "@jupyter-widgets/base",
        top: null,
        grid_column: null,
        overflow_y: null,
        overflow_x: null,
        grid_auto_flow: null,
        grid_area: null,
        grid_template_columns: null,
        flex: null,
        _model_name: "LayoutModel",
        justify_items: null,
        grid_row: null,
        max_height: null,
        align_content: null,
        visibility: null,
        align_self: null,
        height: null,
        min_height: null,
        padding: null,
        grid_auto_rows: null,
        grid_gap: null,
        max_width: null,
        order: null,
        _view_module_version: "1.2.0",
        grid_template_areas: null,
        object_position: null,
        object_fit: null,
        grid_auto_columns: null,
        margin: null,
        display: null,
        left: null,
      },
    },
    "389cbfc5e0dd4bfd99a1881f0b408156": {
      model_module: "@jupyter-widgets/controls",
      model_name: "SliderStyleModel",
      state: {
        _view_name: "StyleView",
        handle_color: null,
        _model_name: "SliderStyleModel",
        description_width: "",
        _view_module: "@jupyter-widgets/base",
        _model_module_version: "1.5.0",
        _view_count: null,
        _view_module_version: "1.2.0",
        _model_module: "@jupyter-widgets/controls",
      },
    },
    b44b6db482b04c55bf7345caa48419e7: {
      model_module: "@jupyter-widgets/base",
      model_name: "LayoutModel",
      state: {
        _view_name: "LayoutView",
        grid_template_rows: null,
        right: null,
        justify_content: null,
        _view_module: "@jupyter-widgets/base",
        overflow: null,
        _model_module_version: "1.2.0",
        _view_count: null,
        flex_flow: null,
        width: null,
        min_width: null,
        border: null,
        align_items: null,
        bottom: null,
        _model_module: "@jupyter-widgets/base",
        top: null,
        grid_column: null,
        overflow_y: null,
        overflow_x: null,
        grid_auto_flow: null,
        grid_area: null,
        grid_template_columns: null,
        flex: null,
        _model_name: "LayoutModel",
        justify_items: null,
        grid_row: null,
        max_height: null,
        align_content: null,
        visibility: null,
        align_self: null,
        height: null,
        min_height: null,
        padding: null,
        grid_auto_rows: null,
        grid_gap: null,
        max_width: null,
        order: null,
        _view_module_version: "1.2.0",
        grid_template_areas: null,
        object_position: null,
        object_fit: null,
        grid_auto_columns: null,
        margin: null,
        display: null,
        left: null,
      },
    },
    bf0d78a072ca4ecd8ab2da9d609af582: {
      model_module: "@jupyter-widgets/controls",
      model_name: "SliderStyleModel",
      state: {
        _view_name: "StyleView",
        handle_color: null,
        _model_name: "SliderStyleModel",
        description_width: "",
        _view_module: "@jupyter-widgets/base",
        _model_module_version: "1.5.0",
        _view_count: null,
        _view_module_version: "1.2.0",
        _model_module: "@jupyter-widgets/controls",
      },
    },
    "454bb9c66647447bb5af1b8c0c44b089": {
      model_module: "@jupyter-widgets/base",
      model_name: "LayoutModel",
      state: {
        _view_name: "LayoutView",
        grid_template_rows: null,
        right: null,
        justify_content: null,
        _view_module: "@jupyter-widgets/base",
        overflow: null,
        _model_module_version: "1.2.0",
        _view_count: null,
        flex_flow: null,
        width: null,
        min_width: null,
        border: null,
        align_items: null,
        bottom: null,
        _model_module: "@jupyter-widgets/base",
        top: null,
        grid_column: null,
        overflow_y: null,
        overflow_x: null,
        grid_auto_flow: null,
        grid_area: null,
        grid_template_columns: null,
        flex: null,
        _model_name: "LayoutModel",
        justify_items: null,
        grid_row: null,
        max_height: null,
        align_content: null,
        visibility: null,
        align_self: null,
        height: null,
        min_height: null,
        padding: null,
        grid_auto_rows: null,
        grid_gap: null,
        max_width: null,
        order: null,
        _view_module_version: "1.2.0",
        grid_template_areas: null,
        object_position: null,
        object_fit: null,
        grid_auto_columns: null,
        margin: null,
        display: null,
        left: null,
      },
    },
    af8f54e0b1644171a2ef24959367b58a: {
      model_module: "@jupyter-widgets/base",
      model_name: "LayoutModel",
      state: {
        _view_name: "LayoutView",
        grid_template_rows: null,
        right: null,
        justify_content: null,
        _view_module: "@jupyter-widgets/base",
        overflow: null,
        _model_module_version: "1.2.0",
        _view_count: null,
        flex_flow: null,
        width: null,
        min_width: null,
        border: null,
        align_items: null,
        bottom: null,
        _model_module: "@jupyter-widgets/base",
        top: null,
        grid_column: null,
        overflow_y: null,
        overflow_x: null,
        grid_auto_flow: null,
        grid_area: null,
        grid_template_columns: null,
        flex: null,
        _model_name: "LayoutModel",
        justify_items: null,
        grid_row: null,
        max_height: null,
        align_content: null,
        visibility: null,
        align_self: null,
        height: null,
        min_height: null,
        padding: null,
        grid_auto_rows: null,
        grid_gap: null,
        max_width: null,
        order: null,
        _view_module_version: "1.2.0",
        grid_template_areas: null,
        object_position: null,
        object_fit: null,
        grid_auto_columns: null,
        margin: null,
        display: null,
        left: null,
      },
    },
    c47964ff73464a8196f6cab80137839f: {
      model_module: "jupyter-leaflet",
      model_name: "LeafletTileLayerModel",
      state: {
        _view_name: "LeafletTileLayerView",
        _view_module: "jupyter-leaflet",
        max_zoom: 9,
        _model_module_version: "^0.14.0",
        _view_count: null,
        visible: true,
        min_zoom: 1,
        tms: false,
        _model_module: "jupyter-leaflet",
        loading: false,
        bottom: true,
        no_wrap: false,
        tile_size: 256,
        popup_min_width: 50,
        opacity: 1,
        popup: null,
        attribution:
          '\nImagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (<a href="https://earthdata.nasa.gov">ESDIS</a>) with funding provided by NASA/HQ.\n',
        _model_name: "LeafletTileLayerModel",
        max_native_zoom: 18,
        base: false,
        min_native_zoom: 0,
        show_loading: false,
        name: "NASAGIBS.ModisTerraTrueColorCR",
        url: "https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2017-04-08/GoogleMapsCompatible_Level9/{z}/{y}/{x}.jpg",
        popup_max_height: null,
        popup_max_width: 300,
        detect_retina: false,
        _view_module_version: "^0.14.0",
        options: [
          "attribution",
          "detect_retina",
          "max_native_zoom",
          "max_zoom",
          "min_native_zoom",
          "min_zoom",
          "no_wrap",
          "tile_size",
          "tms",
        ],
      },
    },
    "3d00982c2f0d45568fa1f006f954f07f": {
      model_module: "jupyter-leaflet",
      model_name: "LeafletMapStyleModel",
      state: {
        _view_name: "StyleView",
        _model_name: "LeafletMapStyleModel",
        _view_module: "@jupyter-widgets/base",
        _model_module_version: "^0.14.0",
        _view_count: null,
        cursor: "grab",
        _view_module_version: "1.2.0",
        _model_module: "jupyter-leaflet",
      },
    },
    bca6b492296948ffaf8648e0a9821974: {
      model_module: "jupyter-leaflet",
      model_name: "LeafletMapStyleModel",
      state: {
        _view_name: "StyleView",
        _model_name: "LeafletMapStyleModel",
        _view_module: "@jupyter-widgets/base",
        _model_module_version: "^0.14.0",
        _view_count: null,
        cursor: "move",
        _view_module_version: "1.2.0",
        _model_module: "jupyter-leaflet",
      },
    },
    "57e88daade524f2897f3bc422fa7dd9d": {
      model_module: "@jupyter-widgets/base",
      model_name: "LayoutModel",
      state: {
        _view_name: "LayoutView",
        grid_template_rows: null,
        right: null,
        justify_content: null,
        _view_module: "@jupyter-widgets/base",
        overflow: null,
        _model_module_version: "1.2.0",
        _view_count: null,
        flex_flow: null,
        width: null,
        min_width: null,
        border: null,
        align_items: null,
        bottom: null,
        _model_module: "@jupyter-widgets/base",
        top: null,
        grid_column: null,
        overflow_y: null,
        overflow_x: null,
        grid_auto_flow: null,
        grid_area: null,
        grid_template_columns: null,
        flex: null,
        _model_name: "LayoutModel",
        justify_items: null,
        grid_row: null,
        max_height: null,
        align_content: null,
        visibility: null,
        align_self: null,
        height: null,
        min_height: null,
        padding: null,
        grid_auto_rows: null,
        grid_gap: null,
        max_width: null,
        order: null,
        _view_module_version: "1.2.0",
        grid_template_areas: null,
        object_position: null,
        object_fit: null,
        grid_auto_columns: null,
        margin: null,
        display: null,
        left: null,
      },
    },
    "1ec10448de0c43be8272046e2309278d": {
      model_module: "jupyter-leaflet",
      model_name: "LeafletMapStyleModel",
      state: {
        _view_name: "StyleView",
        _model_name: "LeafletMapStyleModel",
        _view_module: "@jupyter-widgets/base",
        _model_module_version: "^0.14.0",
        _view_count: null,
        cursor: "grab",
        _view_module_version: "1.2.0",
        _model_module: "jupyter-leaflet",
      },
    },
    "34baf5762f2344e19200892a8efafc27": {
      model_module: "jupyter-leaflet",
      model_name: "LeafletMapModel",
      state: {
        _view_name: "LeafletMapView",
        keyboard_pan_offset: 80,
        right: 0,
        tap: true,
        _view_module: "jupyter-leaflet",
        max_zoom: 18,
        _model_module_version: "^0.14.0",
        _view_count: null,
        zoom_snap: 1,
        min_zoom: 1,
        bounce_at_zoom_limits: true,
        keyboard: true,
        north: 0,
        scroll_wheel_zoom: false,
        dragging: true,
        _model_module: "jupyter-leaflet",
        zoom_delta: 1,
        close_popup_on_click: true,
        fullscreen: false,
        style: "IPY_MODEL_1ec10448de0c43be8272046e2309278d",
        layout: "IPY_MODEL_57e88daade524f2897f3bc422fa7dd9d",
        bottom: 0,
        inertia_max_speed: 1500,
        top: 9007199254740991,
        box_zoom: true,
        controls: [
          "IPY_MODEL_41f57cfcf4674b5298525dfd6ae9ee93",
          "IPY_MODEL_8b3aad421d6f43718708c75e4aa0f9ce",
        ],
        default_style: "IPY_MODEL_3d00982c2f0d45568fa1f006f954f07f",
        east: 0,
        double_click_zoom: true,
        interpolation: "bilinear",
        layers: ["IPY_MODEL_c47964ff73464a8196f6cab80137839f"],
        dragging_style: "IPY_MODEL_bca6b492296948ffaf8648e0a9821974",
        _dom_classes: [],
        zoom_animation_threshold: 4,
        _model_name: "LeafletMapModel",
        zoom_start: 12,
        modisdate: "yesterday",
        keyboard_zoom_offset: 1,
        inertia_deceleration: 3000,
        inertia: true,
        crs: {
          name: "EPSG3857",
          custom: false,
        },
        center: [52.204793, 360.121558],
        zoom: 4,
        world_copy_jump: false,
        _view_module_version: "^0.14.0",
        window_url: "",
        tap_tolerance: 15,
        west: 0,
        touch_zoom: true,
        options: [
          "bounce_at_zoom_limits",
          "box_zoom",
          "center",
          "close_popup_on_click",
          "double_click_zoom",
          "dragging",
          "fullscreen",
          "inertia",
          "inertia_deceleration",
          "inertia_max_speed",
          "interpolation",
          "keyboard",
          "keyboard_pan_offset",
          "keyboard_zoom_offset",
          "max_zoom",
          "min_zoom",
          "scroll_wheel_zoom",
          "tap",
          "tap_tolerance",
          "touch_zoom",
          "world_copy_jump",
          "zoom",
          "zoom_animation_threshold",
          "zoom_delta",
          "zoom_snap",
          "zoom_start",
        ],
        south: 0,
        left: 9007199254740991,
      },
    },
    "41f57cfcf4674b5298525dfd6ae9ee93": {
      model_module: "jupyter-leaflet",
      model_name: "LeafletZoomControlModel",
      state: {
        _view_name: "LeafletZoomControlView",
        zoom_in_title: "Zoom in",
        _model_name: "LeafletZoomControlModel",
        _view_module: "jupyter-leaflet",
        _model_module_version: "^0.14.0",
        _view_count: null,
        _view_module_version: "^0.14.0",
        zoom_out_title: "Zoom out",
        position: "topleft",
        zoom_in_text: "+",
        _model_module: "jupyter-leaflet",
        options: [
          "position",
          "zoom_in_text",
          "zoom_in_title",
          "zoom_out_text",
          "zoom_out_title",
        ],
        zoom_out_text: "-",
      },
    },
    "8b3aad421d6f43718708c75e4aa0f9ce": {
      model_module: "jupyter-leaflet",
      model_name: "LeafletAttributionControlModel",
      state: {
        _view_name: "LeafletAttributionControlView",
        prefix: "ipyleaflet",
        _model_name: "LeafletAttributionControlModel",
        _view_module: "jupyter-leaflet",
        _model_module_version: "^0.14.0",
        _view_count: null,
        _view_module_version: "^0.14.0",
        position: "bottomright",
        _model_module: "jupyter-leaflet",
        options: ["position", "prefix"],
      },
    },
  };
}

window.x = f();
