#!/usr/bin/env bash
echo "setup theme: KUCALC_MODE = " ${KUCALC_MODE:-undefined}
rm -f smc-util/theme.coffee
if [ -z $KUCALC_MODE ]; then
    echo "Cocalc Theme"
    cp -l smc-util/theme-cocalc.coffee smc-util/theme.coffee
else
    echo "Kucalc Theme"
    cp -l smc-util/theme-kucalc.coffee smc-util/theme.coffee
fi