#!/usr/bin/env bash

set -e

umask 022   # always do this so that the resulting build is usable without painful permission hacking.

# The following branch fricas-aldor-local works with the installed debian version.
# It should also work with newer versions, but one never knows.
# It's a patch series that is not yet in the official FriCAS SVN repo.
git clone https://github.com/hemmecke/fricas.git fricas
cd fricas
git checkout -b fricas-aldor-local origin/fricas-aldor-local

# We build FriCAS inside it's source tree and install into /usr/local/
./configure --enable-aldor --with-lisp=sbcl --enable-gmp --prefix=/usr/local
time make -j10 > make.log 2>&1
make install
cd ..
rm -rf fricas
