#!/usr/bin/env bash

set -e
set -v

cd `dirname $0`/..
. smc-env

# npm ci install function, will run in parallel if gnu parallel is installed
run_install() {
    cd "$1"
    npm ci
}

# all module directories
. cocalc-dirs.sh

if `hash parallel &> /dev/null`; then

    export -f run_install
    parallel --will-cite --halt now,fail=1 --linebuffer --jobs 3 run_install ::: "${CODE_DIRS[@]}"

else

    for dir in "${CODE_DIRS[@]}"; do
        run_install "$dir"
    done

fi


# after everything is installed, we run some extra jobs


assistant() {
    # assistant example code snippets
    cd $SMC_ROOT
    git submodule update --init
    cd $SMC_ROOT/examples
    env OUTDIR=../webapp-lib/examples make
}

colors() {
    # generating color scheme
    cd $SMC_ROOT
    scripts/update_color_scheme.coffee
}

react_static() {
    # static react pages update must come *before* webpack
    cd $SMC_ROOT
    update_react_static
}

# run extras in the background
assistant &
colors &
react_static &

wait # for all background processes to finish
echo "ALL DONE"
