#!/usr/bin/env bash

set -e
set -v

cd `dirname $0`/..
. smc-env

# npm audit fix is disabled, because sometimes it errors saying that
# the "endpoint is not available"
run_install() {
    cd "$1"
    npm install
    npm install --only=dev
    #npm audit fix
}

run_install $SMC_ROOT
run_install $SMC_ROOT/smc-util
run_install $SMC_ROOT/smc-util-node
run_install $SMC_ROOT/smc-project
run_install $SMC_ROOT/smc-project/jupyter
run_install $SMC_ROOT/smc-webapp
run_install $SMC_ROOT/smc-webapp/jupyter
run_install $SMC_ROOT/smc-hub

# get rid of package-lock files
# DISABLED: causes build issues; we need to understand npm better
#git ls-files '../*/package-lock.json' | xargs rm -f

# assistant example code snippets
cd $SMC_ROOT
git submodule update --init
cd $SMC_ROOT/examples
env OUTDIR=../webapp-lib/examples make

# generating color scheme
cd $SMC_ROOT
scripts/update_color_scheme.coffee

# static react pages update must come *before* webpack
cd $SMC_ROOT
update_react_static
