#!/usr/bin/env bash

# Ensure that the environment is setup; in particular, SMC_DB_HOSTS is defined
. $HOME/.smc-conf

# This is what might go in crontab:
# 30 */12 * * * /home/salvus/salvus/salvus/scripts/smc-blob-maintenance > /home/salvus/.blob-maintenance.log 2>/home/salvus/.blob-maintenance.err

cd $HOME/smc/src
. smc-env
hub --blob_maintenance --database_nodes=$SMC_DB_HOSTS
