#!/usr/bin/env python

import os, sys, time

n = sys.argv[1]
if '@' in n:
    user, host = n.split('@')
    user = user + '@'
else:
    user = ''
    host = n

print "\ntrying to ssh in:"

while True:
    t = time.time()
    s = "ssh -o ConnectTimeout=3 -o StrictHostKeyChecking=no %s%s"%(user, host)
    print s
    os.system(s)
    time.sleep(1)

