#!/usr/bin/env bash

# Ensure that the environment is setup; in particular, SMC_DB_HOSTS is defined
. $HOME/.smc-conf

# This is what might go in crontab
# 30 0 * * * /home/salvus/salvus/salvus/scripts/sync_stripe > /home/salvus/.sync_stripe.log 2>/home/salvus/.sync_stripe.err

cd $HOME/smc/src
. smc-env
hub --stripe_sync --database_nodes=$PGHOST
