# update the colorscheme definitions

fs = require('fs')
path = require('path')
{COLORS} = require('smc-util/theme')

# write sass file
process.chdir(path.join(process.env['SMC_ROOT'], 'smc-webapp'))

isObject = (a) ->
    (!!a) and (a.constructor == Object)

colors_sass = '/* DO NOT UPDATE THIS FILE -- autogenerated via scripts/update_color_scheme.coffee based on smc-util/theme.coffee */\n\n'
for c, v of COLORS
    # there are nested definitions
    if isObject(v)
        for c2, v2 of v
            colors_sass += "$COL_#{c}_#{c2}: #{v2}\n"
    else
        colors_sass += "$COL_#{c}: #{v}\n"

fs.writeFileSync('_colors.sass', colors_sass)
