#!/usr/bin/env coffee
# update the colorscheme definitions

fs = require('fs')
path = require('path')
{COLORS} = require('smc-webapp/colors')

# write sass file
process.chdir(path.join(process.env['SMC_ROOT'], 'smc-webapp'))

colors_sass = '/* DO NOT UPDATE THIS FILE -- autogenerated via scripts/update_color_scheme.coffee based on ./colors.coffee */\n\n'
for c, v of COLORS
    colors_sass += "$COL_#{c}: #{v}\n"

fs.writeFileSync('_colors.sass', colors_sass)