#!/usr/bin/env python

import os
path = os.path.split(os.path.realpath(__file__))[0]
print(path)

os.chdir(path)

out = open("static/index.html","w")

for X in open("static/html/index.html").readlines():
    print(X)
    if ".html" in X:
       out.write(open(os.path.join("static/html/", X.strip())).read())
    else:
       out.write(X)

    
