#!/usr/bin/env bash

echo "sage_server $@"

if [ x"$1" == x"start" ]; then
    sage "$SAGEMATHCLOUD"/sage_server.py --pidfile "$SAGEMATHCLOUD"/data/sage_server.pid --logfile "$SAGEMATHCLOUD"/data/sage_server.log -d
fi

if [ x"$1" == x"stop" ]; then
   if [ -f "$SAGEMATHCLOUD"/data/sage_server.pid ]; then
       kill `cat "$SAGEMATHCLOUD"/data/sage_server.pid`
       rm "$SAGEMATHCLOUD"/data/sage_server.pid
   fi
fi
