#!/usr/bin/env bash

echo "sage_server $@"

if [ x"$1" == x"start" ]; then
    sage "$SAGEMATHCLOUD"/sage_server.py --pidfile "$HOME"/.sagemathcloud/data/sage_server.pid --logfile "$HOME"/.sagemathcloud/data/sage_server.log -d
fi

if [ x"$1" == x"stop" ]; then
   if [ -f "$HOME"/.sagemathcloud/data/sage_server.pid ]; then
       kill `cat "$HOME"/.sagemathcloud/data/sage_server.pid`
       rm "$HOME"/.sagemathcloud/data/sage_server.pid
   fi
fi
