#!/usr/bin/env bash

P=`pwd`

export SALVUS_ROOT="$P"


export SALVUS_TOKENS="$SALVUS_ROOT"/data/tokens

mkdir -p "$SALVUS_TOKENS"; chmod og-rwx "$SALVUS_TOKENS"   # very important that permissions are restrictive here!

if [ -d /mnt/backup ]; then
   export SALVUS_BACKUP=/mnt/backup/
else
   export SALVUS_BACKUP="$SALVUS_ROOT"/data/backup/
fi

#export BUP_DIR=$SALVUS_BACKUP/bup

export PATH=$P:$P/scripts/gce:$P/node_modules/.bin/:$P/data/local/bin:$P/data/local/sbin:$P/data/local/cassandra/bin:$P/scripts:$PATH

export LD_LIBRARY_PATH=$P/data/local/lib:$LD_LIBRARY_PATH

