window.smc = {}

# The client_browser module provides the API and connection between
# the web browser and a backend hub server.  All websocket-based
# communication goes through here.
client_browser = require('./client_browser')

require './page/top_navbar'
require './page/flux'
require './page/feature'
require './page/colorpicker'
require './page/buttonbar'
require './page/misc_page'
require './page/wizard'
require './page/salvus_client'
require './page/r_misc'
require './page/customize'
require './page/billing'
require './page/alerts'
require './page/3d'
require './page/d3'
require './page/console'
require './page/account'
require './page/syncdoc'
require './page/syncdb'
require './page/tasks'
require './page/archive'
require './page/jupyter'
require './page/profile'
require './page/interact'
require './page/users'
require './page/dropbox'
require './page/project'
require './page/projects'
require './page/project_store'
require './page/project_miniterm'
require './page/project_new'
require './page/project_files'
require './page/project_log'
require './page/project_settings'
require './page/editor_chat'
require './page/file_use'
require './page/exit_confirmation'
require './page/history'
require './page/r_misc'
require './page/r_account'
require './page/r_help'
require './page/system_notifications'
require './page/project_search'
require './page/r_upgrades'
require './page/last'
