#!/usr/bin/env bash

npm install coffee-script
npm install async
npm install winston
npm install temp
npm install commander
npm install start-stop-daemon
npm install pty.js
npm install posix
npm install node-uuid
npm install googlediff
npm install express
npm install underscore
