#!/usr/bin/env python

######################################################################
# This is a daemon-ization script for the IPython notebook, for running
# it under a specific URL behind a given proxy server.  It is probably
# only of use directly in https://cloud.sagemath.com.
#
# Copyright (c) 2013, William Stein, All rights reserved.
# 2-clause BSD:
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the SageMath Project.
######################################################################


import json, os, random, signal, sys, time

# When run in Daemon mode, it stores info (e.g., pid, port) in this file, in addition to printing
# to standard out.  This avoids starting a redundant copy of the daemon, if one is already running.
DAEMON_FILE = ".ipython-daemon.json"

if len(sys.argv) == 1:
    print "Usage: %s [start/stop/status/run] normal ipython notebook options..."%sys.argv[0]
    print "If start or stop is given, then runs as a daemon; otherwise, runs in the foreground."
    sys.exit(1)

mode = sys.argv[1]
del sys.argv[1]


info = json.loads(open(os.path.join(os.environ['HOME'], '.sagemathcloud', 'info.json')).read())

project_id = info['project_id']

ip = info['location']['host']
if ip == 'localhost':
    ip = '127.0.0.1'  # special case for local devel user (not part of public sagemath cloud)

def random_port():
    # get an available port; a race condition is possible, but very, very unlikely.
    while True:
        port = random.randint(1025,65536)
        a = os.popen("netstat -ano|grep %s|grep LISTEN"%port).read()
        if len(a) < 5:
            return port

def command():
    port = random_port()
    base = "/%s/port/%s/"%(project_id, port)
    cmd = "ipython notebook --port-retries=0 --pylab=inline --matplotlib=inline --no-browser --NotebookApp.mathjax_url=/mathjax/MathJax.js  --NotebookApp.base_project_url=%s --NotebookApp.base_kernel_url=%s --ip=%s --port=%s"%(base, base, ip, port)
    cmd += " " + ' '.join(sys.argv[1:])
    return cmd, base, port

if '--help' in ''.join(sys.argv):
    os.system("ipython " + ' '.join(sys.argv))
    sys.exit(0)

def is_daemon_running():
    if not os.path.exists(DAEMON_FILE):
        return False
    try:
        s = open(DAEMON_FILE).read()
        info = json.loads(s)
        try:
            os.kill(info['pid'],0)
            # process exists
            return info
        except OSError:
            # error if no process
            return False
    except:
        # status file corrupted, so ignore it, and
        # just fall through to the below....
        return False


def action():
    cmd, base, port = command()

    if mode == 'status':
        info = is_daemon_running()
        if info:
            info['status'] = 'running'
            s = info
        else:
            s = {'status':'stopped'}
        print json.dumps(s)
        return

    elif mode == 'start':
        info = is_daemon_running()
        if info:
            # already running -- nothing to do
            print json.dumps(info)
            return

        #### First a version check, which is critical due to base url bug(s).

        if os.popen('ipython --version').read().startswith('0.'):
            print json.dumps({"error":"You *must* use IPython version at least 1.0.0, due to show stopper bugs in base_url in all previous versions."})
            sys.exit(1)

        ####

        # The below approach to finding the PID is *HIDEOUS* and could in theory break.
        # It is the only way I could come up with to do this without modifying source code of ipython :-(
        # See http://mail.scipy.org/pipermail/ipython-user/2012-May/010043.html

        c = '%s 2>/dev/null >/dev/null &'%cmd
        os.system(c)

        tries = 0
        pid = 0
        while not pid:
            tries += 1
            if tries >= 50:
                print json.dumps({"error":"Failed to find pid of subprocess."})
                sys.exit(1)

            c = "ps -u`whoami` -o pid,cmd|grep port=%s"%port
            for s in os.popen(c).read().splitlines():
                if '/ipython notebook' in s:
                    pid = int(s.split()[0])
                    break

            if not pid:
                time.sleep(.2)
                continue

        s = json.dumps({'base':base, 'port':port, 'pid':pid})
        print s
        open(DAEMON_FILE,'w').write(s)

    elif mode == 'stop':
        info = is_daemon_running()
        if not info:
            # not running -- nothing to do
            return
        # IPython server seems rock solid about responding to kill signals and properly cleaning up.
        try:
            os.kill(info['pid'], signal.SIGTERM)
        except OSError:  # maybe already dead
            pass
        try:
            os.unlink(DAEMON_FILE)
        except:
            pass


    elif mode == 'run':
        print cmd + '\n\n'
        print "*"*80 + '\n'
        print "  The IPython Notebook server is running at \n"
        print "      https://cloud.sagemath.com%s\n"%base
        print "  All collaborators on this project may access the notebook at the"
        print "  above SSL-encrypted URL, but nobody else can access it."
        print '\n\n' + "*"*80 + '\n\n'
        os.system(cmd + "  2>&1 | grep -v running ")

action()
