#!/usr/bin/env python

import os, sys,time

os.chdir(os.environ['HOME'])

def cmd(s):
    print s
    if os.system(". $HOME/.sagemathcloud/sagemathcloud-env && " + s):
       sys.exit(1)

cmd("cd $HOME/.sagemathcloud && ./make_coffee")

cmd("local_hub start")

# we redirect to /dev/null to detach file descripts so remote ssh terminates without waiting for these.
cmd("console_server start  </dev/null >/dev/null 2>&1 &")

# For now we do NOT background the sage server, since we run into serious problems if a session is requested, but the server isn't started.
cmd("sage_server    start  </dev/null >/dev/null 2>&1 ")

port_files = [".sagemathcloud/data/%s.port"%s for s in ['local_hub', 'console_server', 'sage_server']]

def started():
    for p in port_files:
        if not os.path.exists(p):
            return False
    return True

# wait (up to 15 seconds) until the port files get created
i=0
while not started():
    time.sleep(0.1)
    i += 1
    print i
    if i >= 150:
        sys.stderr.write("Error allocating network port\n")
        sys.exit(1)


