#!/usr/bin/env python

SMC = '.sagemathcloud'

import json, os, sys

os.chdir(os.environ['HOME'])

if len(sys.argv) == 1:
    sys.stderr.write("Usage: %s project_path"%sys.argv[0])
    sys.exit(1)

status = {}
def done():
    print json.dumps(status)
    sys.exit(0)
def set(prop, val):
    status[prop] = val
    if val is False:
        done()
def read(prop, filename, strip=False):
    try:
        s = open(filename).read()
        if strip:
            s = s.strip()
        status[prop] = s
    except:
        status[prop] = False
        done()

read('version', os.path.join(os.environ['HOME'], SMC, "version"), strip=True)

# a simple test that the node modules are probably installed.
set('installed', os.path.exists(os.path.join(os.environ['HOME'], SMC, 'node_modules/pty.js')))

project_path = os.path.join(os.environ['HOME'], sys.argv[1])
set('project_path_exists', os.path.exists(project_path))

conf_path    = os.path.join(project_path, SMC)
set('conf_path_exists',    os.path.exists(conf_path))

for name in ['secret_token', 'local_hub.port']:
    read(name, os.path.join(project_path, SMC, name))

set('disk_usage', int(os.popen('du -s "%s"'%project_path).read().split()[0]))

done()

