#!/usr/bin/env bash

echo "Read SageMathCloud environment variables."
. "$HOME"/.sagemathcloud/sagemathcloud-env

echo "Remove port files."
rm  "$HOME"/.sagemathcloud/data/*.port

echo "Stop daemons."
local_hub      stop
console_server stop
sage_server    stop
