#!/usr/bin/env bash

echo "Read SageMathCloud environment variables."
. $HOME/.sagemathcloud/sagemathcloud-env

if [ -d "$1" ]; then
    cd "$1"
    rm .sagemathcloud/*.port
    local_hub stop
    console_server stop
    #sage_server stop
fi