#!/usr/bin/env bash

# Start the three services running in a new tmux session called "smc": hub, datatabase, and webpack

tmux new-session -s smc -d './start_rethinkdb.py' \; split-window -d './start_hub.py' \; split-window -d './start_webpack.py' \; split-window -d './info.py' \; attach
