#!/usr/bin/env bash

. /home/salvus/.ssh/agent

# from http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

$DIR/push_conf.py
