#!/usr/bin/env python

import os
BUP_DIR=os.environ['BUP_DIR']='/backup/dc2/cassandra2-3/'

def cmd(s):
    print s
    os.system(s)

cmd("bup init")
for dc in [3,4]:
    for i in range(1,5):
        host = "10.%s.%s.2"%(dc, i)
        cmd("time bup on %s init"%host)
        cmd("time bup on %s index /mnt/cassandra"%host)
        cmd("time bup on %s save /mnt/cassandra -n %s"%(host, host))
 
