#!/usr/bin/env python

import os
target = "%s/vm/images/cassandra/"%os.environ['HOME']

BWLIMIT=5000 # 

BUP_DIR=os.environ['BUP_DIR']="%s/vm/images/cassandra-bup"%os.environ["HOME"]

def cmd(s):
    print s
    os.system(s)

for i in range(1,8):
    host = "10.1.%s.2"%i
    cmd("time rsync -axvH --delete --bwlimit=%s %s:/mnt/cassandra/ %s/"%(BWLIMIT, host, os.path.join(target, 'cassandra%s'%i)))

cmd("time bup index %s"%target)
cmd("time bup save %s -n cassandra"%target)

cmd("time rsync -axvH %s disk:cassandra-bup/"%BUP_DIR)
