#!/usr/bin/env python

import os
target = "%s/vm/images/cassandra/"%os.environ['HOME']

BWLIMIT=5000 # 5MB/s

for i in range(1,8):
    host = "10.1.%s.2"%i
    s = "rsync -axvH --delete --bwlimit=%s %s:/mnt/cassandra/ %s/"%(BWLIMIT, host, os.path.join(target, 'cassandra%s'%i))
    print s
    os.system(s)
