/* File context, for rendering files on the share server. */

//
//     const context = useFrameContext();
//
// inside of any component being used inside of a CoCalc frame,
// and you get the project_id, path, and id of that particular
// frame, and probably more as we need it.

import React, { createContext, useContext, ReactNode } from "react";

interface IFileContext {
  // allow customizing anchor tags that get generated by various components, e.g., Markdown via slate.
  AnchorTagComponent?: React.FC<{
    href?: string;
    children?: ReactNode;
    title?: string;
    attributes?;
    id?;
  }>;

  // Allow customizing the header tags that get generated, e.g., this is used to add the linkable
  // headers in markdown in Jupyter notebooks (to match how Jupyter classic works).
  HeadingTagComponent?: React.FC<{
    level?: number;
    children?: ReactNode;
    attributes?;
    id?;
  }>;

  // If given, then when an anchor (A) tag is clicked
  // on, the given function is called.
  anchorTagAction?: (url: string) => void;

  // If given, then all href and src attributes in all
  // tags are transformed by urlTransform, except anchor
  // tags if anchorTagAction is defined.  If it returns
  // undefined, they are unchanged; if it returns a string,
  // they are replaced by that.
  urlTransform?: (url: string, tag?: string) => string | undefined;

  noSanitize?: boolean;

  // If true, when rendering append a random query param after the source of any image
  // to force it to reload.  This is, e.g., useful for R markdown, where each time it
  // updates, the images may change, by their names don't, so we have to break the browser cache.
  reloadImages?: boolean;
}

export const FileContext = createContext<IFileContext>({});

export const useFileContext = () => {
  return useContext(FileContext);
};
