#!/usr/bin/env python

import os

target = "/home/salvus/vm/images/bup/bups"

if not os.path.exists(target):
    os.makedirs(target)

def cmd(s):
    print s
    return os.popen(s).read()

def cmd2(s):
    print s
    if os.system(s):
        print "WARNING!!"
    return

cmd("bup init")

for i in range(10,22):
    host = '10.1.%s.5'%i
    print host
    cmd2("rsync -axvH  --bwlimit 20000 --delete root@%s:/bup/bups/ %s/%s/"%(host, target, host))
