#!/usr/bin/env python

import os

os.environ['BUP_DIR']="/backup/bups-bup"

def cmd(s):
    print s
    os.system(s)

cmd("bup init")

v=['c2ba4efc-8b4d-4447-8b0b-6a512e1cac97',
 'f71dab5b-f40c-48db-a3d2-eefe6ec55f01',
 '8f5247e5-d449-4356-9ca7-1d971c79c7df',
 '94d4ebc1-d5fc-4790-affe-ab4738ca0384',
 '806edbba-a66b-4710-9c65-47dd70503fc9',
 '0663ed3c-e943-4d46-8c5e-b5e7bd5a61cc',
 'd0bfc232-beeb-4062-9ad5-439c794594f3',
 '44468f71-5e2d-4685-8d60-95c9d703bea0']

for i, server_id in enumerate(v):
    j = 1 + i 
    cmd("time bup on root@10.3.%s.5 init"%j)
    cmd("time bup on root@10.3.%s.5 index /bup/bups"%j)
    cmd("time bup on root@10.3.%s.5 save /bup/bups -n %s"%(j, server_id))


