#!/usr/bin/env bash

# Run sync on all projects that aren't currently in sync across all data centers.  This is mainly to handle the
# rare case of a sync failure or when a compute server goes down temporarily.

cd $HOME/salvus/salvus
. salvus-env

time echo "x={};require('bup_server').global_client(cb:(e,c)->x.c=c; x.c.backup_project_locations(cb:(e)->console.log('DONE',e);process.exit() ))" | coffee

