#!/usr/bin/env python
 
import os, sys, time
 
while True:
    c = ' '.join(sys.argv[2:])
    print c
    os.system(c)

    t = int(sys.argv[1]) 
    print "waiting %s seconds..."%t

    time.sleep(t)
