#!/usr/bin/env python

import json, os

branches = [x.split()[-1] for x in os.popen("git branch").read().splitlines()]

files = {}

def set_file(obj, components, commit):
    if len(components) == 1:
        obj[components[0]] = commit
    else:
        if not obj.has_key(components[0]):
            obj[components[0]] = {}
        set_file(obj[components[0]], components[1:], commit) # recurse


for branch in branches:
    d = {}
    files[branch] = d
    for f in os.popen("git ls-tree --full-tree -r " + branch).read().splitlines():
        _, _, obj, filename = f.split()
        r = os.popen("git log -1 -- '%s'|head -1"%filename).readlines()
        if len(r) > 0:
            x = r[0].split()
            if len(x) >= 2:
                commit_id = x[1]
                set_file(d, filename.split('/'), commit_id)

print json.dumps(files,  separators=(',',':'))
