#!/usr/bin/env python

import os, sys

if len(sys.argv) == 2:
    out = sys.argv[1]
else:
    out = "node_modules"

v = []
for src in os.listdir('.'):
    if src.endswith('.coffee'):
        name = src[:-7]
        target = '%s/%s.js'%(out, name)
        if not os.path.exists(target) or os.stat(target).st_mtime < os.stat(src).st_mtime:
            v.append(src)

if v:
    cmd = 'coffee -o %s -c %s'%(out, ' '.join(v))
    print cmd
    if os.system(cmd):
        sys.exit(1)
