#!/usr/bin/env python
"""
(c) William Stein, 2013

The modification times are stored under git in the file .gitmtimes. 
"""

def save_modtimes(path):
    print "saving modtimes"

def restore_modtimes(path):
    print "restoring modtimes"

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="modtimes -- save or restore modification times of all files/directories under this path")
    parser.add_argument('--save', help='save modification times', action='store_true')
    parser.add_argument('--restore', help='restore modification times', action='store_true')
    parser.add_argument('path', nargs='?', help='save or restore modification times of all files/directories under this path')

    args = parser.parse_args()
    if isinstance(args.path, list):
        args.path = args.path[0]

    if args.save:
        save_modtimes(args.path)

    if args.restore:
        restore_modtimes(args.path)

