#!/usr/bin/env python

import os, sys, time

n = sys.argv[1]
if '@' in n:
    user, host = n.split('@')
    user = user + '@'
else:
    user = ''
    host = n

while True:
    addr = os.popen('kvm_addresses.py %s'%host).read().strip()
    if addr:
        break
    print "address not yet known..."
    time.sleep(1)

while True:
    t = time.time()
    s = "ssh %s%s"%(user, addr)
    print s
    os.system(s)
    if time.time()-t > 5:
        break
    else:
        time.sleep(3)

