#!/usr/bin/env python

import os, sys

os.chdir(os.path.split(os.path.realpath(__file__))[0] + '/..')

id = ''
for i in range(1, len(sys.argv)):
    if sys.argv[i] == '--id':
        id = sys.argv[i+1]
        del sys.argv[i]
        break

args = ' '.join(sys.argv[1:])
if id != '':
    cmd="cp run/hub.js run/hub%s.js && node run/hub%s.js %s"%(id, id, args)
else:
    cmd = "node --max-old-space-size=8000 run/hub.js " + args
print cmd

if os.WEXITSTATUS(os.system(cmd)):
    raise RuntimeError
