#!/usr/bin/env bash
set -e
set -v

# Ensure that the environment is setup; in particular, PGHOST
. $HOME/.smc-conf

# This is what might go in crontab:
# 0 */12 * * * /home/salvus/salvus/salvus/scripts/smc-delete-expired > /home/salvus/.delete_expired.log 2>/home/salvus/.delete_expired.err

cd $HOME/smc/src
. smc-env
hub --delete_expired
