#!/usr/bin/env bash
set -e
set -v
cd /home/salvus/smc/src
. smc-env
export PGUSER=smc
export PGHOST=/tmp
export PGDATABASE=smc
time echo "db=require('./smc-hub/postgres').db();db.connect(cb:->db.backup_tables(tables:'critical', path:'/backup/postgres', cb:process.exit, limit:10))" | coffee


# This is what I put in crontab... 
# Dump and snapshot critical tables every 6 hours.
# 0 */6 * * * /home/salvus/smc/src/scripts/postgresql/smc-backup-postgres 1>/home/salvus/.smc-backup-postgres.log 2>/home/salvus/.smc-backup-postgres.err