#!/usr/bin/env python

if __name__ == "__main__":
    import argparse, os

    parser = argparse.ArgumentParser(description="run cassandra")

    parser.add_argument("-c", dest='confdir', type=str)
    parser.add_argument("-p", dest='pidfile', type=str)
    parser.add_argument("-f", dest='foreground', default=False, action="store_const", const=True)

    args = parser.parse_args()
    os.environ['CASSANDRA_CONF'] = args.confdir

    cmd = "%s/../../cassandra/bin/cassandra -p %s %s"%(
              os.path.realpath(__file__), args.pidfile, '-f' if args.foreground else '')
    print cmd
    os.system(cmd)
