#!/usr/bin/env bash
set -ev


export SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "$SCRIPT_DIR"

export SRC="$SCRIPT_DIR"/../

mkdir -p smc-webapp
echo "THIS DIRECTORY IS AUTOGENERATED" > smc-webapp/AUTOGENERATED.txt
mkdir -p smc-util
echo "THIS DIRECTORY IS AUTOGENERATED" > smc-util/AUTOGENERATED.txt

cp $SRC/smc-webapp/file-associations.ts smc-webapp/


mkdir -p smc-webapp/jquery-plugins/
rsync -axvH $SRC/smc-webapp/jquery-plugins/math-katex.ts smc-webapp/jquery-plugins/math-katex.ts

mkdir -p smc-webapp/editors/slate/elements/
rsync -axvH $SRC/smc-webapp/editors/slate/elements/math-to-html.ts smc-webapp/editors/slate/elements/math-to-html.ts

mkdir -p smc-webapp/markdown/
rsync -axvH --delete --exclude /table-of-contents.ts --exclude /index.ts $SRC/smc-webapp/markdown/ smc-webapp/markdown/

rsync -axvH $SRC/smc-util/markdown-utils.ts smc-util/markdown-utils.ts
rsync -axvH $SRC/smc-util/mathjax-utils.js smc-util/mathjax-utils.js
rsync -axvH $SRC/smc-util/replace-all.ts smc-util/replace-all.ts
rsync -axvH $SRC/smc-util/regex-split.js smc-util/regex-split.js

mkdir -p smc-webapp/sagews
rsync -axvH $SRC/smc-webapp/sagews/parse-sagews.ts smc-webapp/sagews/parse-sagews.ts
rsync -axvH $SRC/smc-webapp/sagews/worksheet.tsx smc-webapp/sagews/worksheet.tsx
rsync -axvH $SRC/smc-webapp/sagews/cell.tsx smc-webapp/sagews/cell.tsx
rsync -axvH $SRC/smc-webapp/sagews/input.tsx smc-webapp/sagews/input.tsx
rsync -axvH $SRC/smc-webapp/sagews/output.tsx smc-webapp/sagews/output.tsx
echo 'export function CellOutput(props) { return <pre>{JSON.stringify(props,undefined,2)}</pre>; }' > smc-webapp/sagews/output.tsx
rsync -axvH $SRC/smc-util/sagews.ts smc-util/sagews.ts



