#!/bin/sh

# Source common setup, including hostconfig.
#
. /etc/rc.common

StartService( )
{
    ConsoleMessage "Starting salvus VPN"
    /Users/salvus/salvus/salvus/data/local/sbin/tincd &
}

StopService( )
{
    ConsoleMessage "Stopping salvus VPN"
    killall tincd
}

RestartService( )
{
    ConsoleMessage "Restarting salvus VPN"
    StopService
    StartService
}

RunService "$1"
