// this is based on /usr/share/X11/xkb/rules/evdev.lst
// I have no idea if variants like "nodeadkeys" for german are necessary

export const PHYSICAL_KEYBOARDS = [
  { value: "default", display: "Default (language-based guess)" },
  { value: "us", display: "English (US)" },
  { value: "af", display: "Afghani" },
  { value: "ara", display: "Arabic" },
  { value: "al", display: "Albanian" },
  { value: "am", display: "Armenian" },
  { value: "at", display: "German (Austria)" },
  { value: "au", display: "English (Australian)" },
  { value: "az", display: "Azerbaijani" },
  { value: "by", display: "Belarusian" },
  { value: "be", display: "Belgian" },
  { value: "bd", display: "Bangla" },
  { value: "in", display: "Indian" },
  { value: "ba", display: "Bosnian" },
  { value: "br", display: "Portuguese (Brazil)" },
  { value: "bg", display: "Bulgarian" },
  { value: "dz", display: "Berber (Algeria, Latin)" },
  { value: "ma", display: "Arabic (Morocco)" },
  { value: "cm", display: "English (Cameroon)" },
  { value: "mm", display: "Burmese" },
  { value: "ca", display: "French (Canada)" },
  { value: "cd", display: "French (Democratic Republic of the Congo)" },
  { value: "cn", display: "Chinese" },
  { value: "hr", display: "Croatian" },
  { value: "cz", display: "Czech" },
  { value: "dk", display: "Danish" },
  { value: "nl", display: "Dutch" },
  { value: "bt", display: "Dzongkha" },
  { value: "ee", display: "Estonian" },
  { value: "ir", display: "Persian" },
  { value: "iq", display: "Iraqi" },
  { value: "fo", display: "Faroese" },
  { value: "fi", display: "Finnish" },
  { value: "fr", display: "French" },
  { value: "gh", display: "English (Ghana)" },
  { value: "gn", display: "French (Guinea)" },
  { value: "ge", display: "Georgian" },
  { value: "de", display: "German" },
  { value: "gr", display: "Greek" },
  { value: "hu", display: "Hungarian" },
  { value: "is", display: "Icelandic" },
  { value: "il", display: "Hebrew" },
  { value: "it", display: "Italian" },
  { value: "jp", display: "Japanese" },
  { value: "kg", display: "Kyrgyz" },
  { value: "kh", display: "Khmer (Cambodia)" },
  { value: "kz", display: "Kazakh" },
  { value: "la", display: "Lao" },
  { value: "latam", display: "Spanish (Latin American)" },
  { value: "lt", display: "Lithuanian" },
  { value: "lv", display: "Latvian" },
  { value: "mao", display: "Maori" },
  { value: "me", display: "Montenegrin" },
  { value: "mk", display: "Macedonian" },
  { value: "mt", display: "Maltese" },
  { value: "mn", display: "Mongolian" },
  { value: "no", display: "Norwegian" },
  { value: "pl", display: "Polish" },
  { value: "pt", display: "Portuguese" },
  { value: "ro", display: "Romanian" },
  { value: "ru", display: "Russian" },
  { value: "rs", display: "Serbian" },
  { value: "si", display: "Slovenian" },
  { value: "sk", display: "Slovak" },
  { value: "es", display: "Spanish" },
  { value: "se", display: "Swedish" },
  { value: "ch", display: "German (Switzerland)" },
  { value: "sy", display: "Arabic (Syria)" },
  { value: "tj", display: "Tajik" },
  { value: "lk", display: "Sinhala (phonetic)" },
  { value: "th", display: "Thai" },
  { value: "tr", display: "Turkish" },
  { value: "tw", display: "Taiwanese" },
  { value: "ua", display: "Ukrainian" },
  { value: "gb", display: "English (UK)" },
  { value: "uz", display: "Uzbek" },
  { value: "vn", display: "Vietnamese" },
  { value: "kr", display: "Korean" },
  { value: "nec_vndr/jp", display: "Japanese (PC-98)" },
  { value: "ie", display: "Irish" },
  { value: "pk", display: "Urdu (Pakistan)" },
  { value: "mv", display: "Dhivehi" },
  { value: "za", display: "English (South Africa)" },
  { value: "epo", display: "Esperanto" },
  { value: "np", display: "Nepali" },
  { value: "ng", display: "English (Nigeria)" },
  { value: "et", display: "Amharic" },
  { value: "sn", display: "Wolof" },
  { value: "brai", display: "Braille" },
  { value: "tm", display: "Turkmen" },
  { value: "ml", display: "Bambara" },
  { value: "tz", display: "Swahili (Tanzania)" },
  { value: "tg", display: "French (Togo)" },
  { value: "ke", display: "Swahili (Kenya)" },
  { value: "bw", display: "Tswana" },
  { value: "ph", display: "Filipino" },
  { value: "md", display: "Moldavian" },
  { value: "id", display: "Indonesian (Jawi)" },
  { value: "my", display: "Malay (Jawi, Arabic Keyboard)" }
];

// sort by name, and "default" should be first
PHYSICAL_KEYBOARDS.sort(function(a, b) {
  // a[0], b[0] is the key of the map
  if (a.value === "default") {
    return -1;
  } else if (b.value === "default") {
    return 1;
  } else {
    return a.display.localeCompare(b.display);
  }
});
