#!/usr/bin/env bash
set -ev

cd smc-hub

npm run build

pkill -f run/hub.js || true
pkill -f dist/local_hub.js  || true

NODE_OPTIONS=--enable-source-maps npx cocalc-hub-server --dev --websocket_server  --foreground --host=0.0.0.0 --mentions >out 2>err &

tail -f out err
