#!/usr/bin/env bash
[ -z "$BASH_VERSION" ] && echo "**ABORT**: This script assumes you are running BASH" && return

# a custom MAKE variable breaks building the posix node.js package
unset MAKE

P=`pwd`

# Load the library for bash functions
source scripts/smc-bash-lib

export SALVUS_ROOT="$P"
export SMC_ROOT="$P"  # so can start using SMC_ROOT in scripts

export NODE_PATH="$SALVUS_ROOT/node_modules/smc-util":"$SALVUS_ROOT/node_modules":"$SALVUS_ROOT:$SALVUS_ROOT/smc-project/node_modules"

export SALVUS_TOKENS="$SALVUS_ROOT/data/tokens"
mkdir -p "$SALVUS_TOKENS"; chmod og-rwx "$SALVUS_TOKENS"   # very important that permissions are restrictive here!

if [ -d /mnt/backup ]; then
   export SALVUS_BACKUP=/mnt/backup/
else
   export SALVUS_BACKUP="$SALVUS_ROOT/data/backup/"
fi

#export BUP_DIR=$SALVUS_BACKUP/bup

path_prepend PATH "$SMC_ROOT/scripts"
path_prepend PATH "$SMC_ROOT/data/local/sbin"
path_prepend PATH "$SMC_ROOT/data/local/bin"
path_prepend PATH "$SMC_ROOT/node_modules/.bin/"
path_prepend PATH "$SMC_ROOT/scripts/hub"
path_prepend PATH "$SMC_ROOT/scripts/gce"
path_prepend PATH "$SMC_ROOT/scripts/storage"
path_prepend PATH "$SMC_ROOT/smc-hub/scripts"
path_prepend PATH "$SMC_ROOT"

path_prepend LD_LIBRARY_PATH "$SMC_ROOT/data/local/lib"


