#!/usr/bin/env python

import os, time

print("Building static pages")
os.system("cd $SALVUS_ROOT; . smc-env; npm run webpack-static")

print("Starting webpack")
s = "cd $SALVUS_ROOT; unset CC_STATICPAGES; . smc-env; CC_NOCLEAN=true npm run webpack-watch"
while True:
    print(s)
    os.system(s)
    time.sleep(3)
