#!/bin/sh

set -e
set -v

export NODE_PATH=$SALVUS_ROOT/smc-hub/node_modules/:$NODE_PATH
cd $SALVUS_ROOT/static/primus
node update_primus.js
uglifyjs primus-engine.js > primus-engine.min.js 2>/dev/null
