#!/usr/bin/env bash

set -v

cd /home/salvus/salvus/salvus
. salvus-env

time echo "x={};require('compute').compute_server(db_hosts:['smc0-us-central1-c'], cb:(e,s)->console.log(e);x.s=s;x.s.tar_backup_recent(max_age_h:12, cb:(e)->console.log('DONE',e);process.exit(0)))" | coffee

time gsutil -o GSUtil:parallel_composite_upload_threshold=150M -m rsync -r /backups/ gs://smc-projects-backup/
