#!/usr/bin/env python

import os
logs = "%s/logs"%os.environ['HOME']
m = 0
for x in os.listdir(logs):
    if x.startswith('hub') and x.endswith('.log'):
        s = os.popen("tail -n 100000 %s/%s | grep FEED.*num_feeds=.*changefeeds|tail -n 1"%(logs, x)).read().strip()
        try:
            n = int(s.split('=')[1].split()[0])
        except:
            n = 0
        print("%-10s" % x, n)
        m += n

print("%-10s" % "total", m)
